### ISSUE TITLE
IsADirectory Error on M1 Mac

### ISSUE THREAD

**Issue by winterwarrior3** [carson-katri/dream-textures#10]
Running this addon on my M1 MacBook Pro. After clicking "OK" to generate a texture, the console outputs the following error:

`>> Loading model from /Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-3' coro=<DreamTexture.dream_texture() done, defined at /Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=IsADirectoryError(21, 'Is a directory')>
Traceback (most recent call last):
  File "/Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py", line 136, in dream_texture
    generator.load_model()
  File "/Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 457, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "/Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 578, in _load_model_from_config
    model = instantiate_from_config(c.model)
  File "/Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 657, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 768, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/Users/jakebaine/Library/Application Support/Blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/modules/encoders/modules.py", line 245, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(
  File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1734, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/transformers/utils/hub.py", line 408, in cached_file
    resolved_file = hf_hub_download(
  File "/Applications/Blender.app/Contents/Resources/3.3/python/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1172, in hf_hub_download
    with open(ref_path) as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/jakebaine/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/refs/main'`

I've tried installing the addon two times, completing all steps with no errors.

Running on M1 MacBook Pro 14inch with 16GB of RAM and 14GPU cores. Latest stable release of Blender 3.3.

**Comment by not-that-nda** [comment]
I get the same error though if you delete the "main" directory in the path where it returns the issue you get a "file not found error instead, which is the error I get instead of the one you mention.

Using Blender 3.3 and Ventura Beta 13
