### ISSUE TITLE
Error during instal on Apple M1 Mac

### ISSUE THREAD

**Issue by 3pointedit** [carson-katri/dream-textures#105]
Installing the compressed downloaded file (so mac doesn't unzip), results in :
`Traceback (most recent call last):
  File "/Applications/Blender3.4.app/Contents/Resources/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'dream-textures-0'`

Obviously this is using a recent build 3.4 of Blender. Should I try 3.3 instead?

**Comment by 3pointedit** [comment]
I tried to resolve this by installing local Github on my desktop, then I made a local zip file from there. Once I started from the terminal this imported to addons prefs properly and allowed me to add the Model weights. But when I tried to install dependencies it failed. 

The dependencies downloaded and installed but not all packages could be executed. I do not know how to upgrade the pip version.
Here is the error from the Blender terminal...

> ` Running setup.py install for greenlet ... done
>     Running setup.py install for basicsr ... error
>     ERROR: Command errored out with exit status 1:
>      command: /Applications/Blender3.4.app/Contents/Resources/3.4/python/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-install-b05l1hum/basicsr_083975df7b1141219990c7dd2cfbfeaa/setup.py'"'"'; __file__='"'"'/private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-install-b05l1hum/basicsr_083975df7b1141219990c7dd2cfbfeaa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-record-i9g4ntv_/install-record.txt --single-version-externally-managed --home /private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-target-b27hm4yi --compile --install-headers /private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-target-b27hm4yi/include/python/basicsr
>          cwd: /private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-install-b05l1hum/basicsr_083975df7b1141219990c7dd2cfbfeaa/
>     Complete output (28 lines):
>     WARNING: The wheel package is not available.
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-install-b05l1hum/basicsr_083975df7b1141219990c7dd2cfbfeaa/setup.py", line 147, in <module>
>         setup(
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/setuptools/__init__.py", line 152, in setup
>         _install_setup_requires(attrs)
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
>         dist.fetch_build_eggs(dist.setup_requires)
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
>         resolved_dists = pkg_resources.working_set.resolve(
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/pkg_resources/__init__.py", line 766, in resolve
>         dist = best[req.key] = env.best_match(
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1051, in best_match
>         return self.obtain(req, installer)
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1063, in obtain
>         return installer(requirement)
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
>         return fetch_build_egg(self, req)
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
>         wheel.install_as_egg(dist_location)
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/setuptools/wheel.py", line 95, in install_as_egg
>         self._install_as_egg(destination_eggdir, zf)
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
>         self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
>       File "/Applications/Blender3.4.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
>         os.mkdir(destination_eggdir)
>     FileExistsError: [Errno 17] File exists: '/private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-install-b05l1hum/basicsr_083975df7b1141219990c7dd2cfbfeaa/.eggs/torch-1.12.1-py3.10-macosx-11.00-arm64.egg'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /Applications/Blender3.4.app/Contents/Resources/3.4/python/bin/python3.10 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-install-b05l1hum/basicsr_083975df7b1141219990c7dd2cfbfeaa/setup.py'"'"'; __file__='"'"'/private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-install-b05l1hum/basicsr_083975df7b1141219990c7dd2cfbfeaa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-record-i9g4ntv_/install-record.txt --single-version-externally-managed --home /private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-target-b27hm4yi --compile --install-headers /private/var/folders/rv/ll6q3_3x2vzfl4cp4fgh0vw00000gn/T/pip-target-b27hm4yi/include/python/basicsr Check the logs for full command output.
> WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
> You should consider upgrading via the '/Applications/Blender3.4.app/Contents/Resources/3.4/python/bin/python3.10 -m pip install --upgrade pip' command.
> 
> `

**Comment by 3pointedit** [comment]
Solved by downloading the Release version (which is a bit hard to find). Making sure that Rust installs correctly. Also I made sure to run Blender from inside the package folder (via the terminal startup). I had to restart Blender for the dependencies to be available. Thank you for a cool addon
