### ISSUE TITLE
Problem in fedora 36

### ISSUE THREAD

**Issue by darthmikael** [carson-katri/dream-textures#119]
I have succesfully installed the dependencies in fedoras 36 running blender with SUDO. But still cant generate anything, It seems to start to work, but nothing appears. This is what the console says.

[darthmikael@fedora blender-3.3.0-linux-x64]$ sudo ./blender
Read prefs: /root/.config/blender/3.3/config/userpref.blend
>> Loading model from /root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at /root/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))>
Traceback (most recent call last):
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py", line 136, in dream_texture
    generator.load_model()
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 457, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 578, in _load_model_from_config
    model = instantiate_from_config(c.model)
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 657, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 768, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 99, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/modules/encoders/modules.py", line 7, in <module>
    import kornia
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/__init__.py", line 10, in <module>
    from . import (
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/augmentation/__init__.py", line 43, in <module>
    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/augmentation/container/__init__.py", line 1, in <module>
    from .augment import AugmentationSequential
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/augmentation/container/augment.py", line 17, in <module>
    from .patch import PatchSequential
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/augmentation/container/patch.py", line 9, in <module>
    from kornia.contrib.extract_patches import extract_tensor_patches
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/contrib/__init__.py", line 4, in <module>
    from .image_stitching import ImageStitcher
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/contrib/image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/feature/__init__.py", line 4, in <module>
    from .integrated import (
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/feature/integrated.py", line 52, in <module>
    class LAFDescriptor(nn.Module):
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/feature/integrated.py", line 65, in LAFDescriptor
    patch_descriptor_module: nn.Module = HardNet(True),
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/kornia/feature/hardnet.py", line 66, in __init__
    pretrained_dict = torch.hub.load_state_dict_from_url(
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/torch/hub.py", line 591, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/site-packages/torch/hub.py", line 457, in download_url_to_file
    u = urlopen(req)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/blender-3.3.0-linux-x64/3.3/python/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
/root/.config/blender/3.3/scripts/addons/dream_textures/async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

Thanks in advance for the help

**Comment by dynamodan** [comment]
I also have this error on ubuntu 18.04.  I do have my certificates up to date and even ran the pip install certifi command within the blender bundled python.

**Comment by diramazioni** [comment]
see issue #5

**Comment by darthmikael** [comment]
> see issue #5 
Still having the same error in fedora linux

**Comment by NathanSalapat** [comment]
Have you tried to manually download the file. I had a similar problem with a file not downloading when I tried running the script, but I was able to manually download the file, and place it in the correct place and that fixed the issue for me.

**Comment by diramazioni** [comment]
My advice are: 
Do not run blender as root, running as root can mess things seriously and there is no need.
Start tblender from the terminal from the directory where you have downloaded open a terminal and type:
`SSL_CERT_DIR=/etc/ssl/certs ./blender`
Remove the addon
Install it again and then click install dependencies, watch the terminal from any error in the output.
If this last  step complete successfully you wont have any problem afterwards

**Comment by dynamodan** [comment]
Thanks @diramazioni that worked for me too.  It's because the python `requests` package and the `urllib.request` package look in different places, or maybe `urllib` is just lazy and doesn't look anywhere.  One works fine and the other throws the SSL error (I tried it in blender's python console and found this out).

But using your `SSL_CERT_DIR=/etc/ssl/certs` environment variable worked nicely and everything installed without error.  But I still can't get dream textures to work, it says illegal instruction and core dumped.  I think something is wrong with my CUDA setup.  I have an nVidia GeForce GTX 1650 which is probably incompatible or something.

**Comment by diramazioni** [comment]
@dynamodan maybe insufficient VRAM it needs >3gb.
Have you tried if it works using the webui?
