### ISSUE TITLE
Installing Dependencies Error message (please help!!)

### ISSUE THREAD

**Issue by BeauCotter** [carson-katri/dream-textures#120]
### Discussed in https://github.com/carson-katri/dream-textures/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **BeauCotter** September 23, 2022</sup>
Can someone help me with this...
Whenever I try to install dependencies blender puts out this error

Python: Traceback (most recent call last):
  File "C:\Users\heyco\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\install_dependencies.py", line 140, in execute
    install_pip()
  File "C:\Users\heyco\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\install_dependencies.py", line 55, in install_pip
    subprocess.run([sys.executable, "-m", "pip", "--version"], check=True)
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 1375, in _execute_child
    args = list2cmdline(args)
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "E:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

I have no idea what this means...
I have no experience with Python</div>

**Comment by denis-roy** [comment]
@BeauCotter, duplicating issues is counter-productive.

Skimming through duplicate issues like this one is a maintenance task and while the devs are doing maintenance tasks, they are not improving their software ¯\_(ツ)_/¯

**Comment by carson-katri** [comment]
Version 0.0.6 no longer requires dependencies to be installed. Please upgrade to that version.
