### ISSUE TITLE
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. - Linux

### ISSUE THREAD

**Issue by jurassicjordan** [carson-katri/dream-textures#164]
**Describe the bug**
Attempting to generate a texture fails

**Traceback**
Loading model from /home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at /home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=OSError("Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.")>
Traceback (most recent call last):
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py", line 136, in dream_texture
    generator.load_model()
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 457, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 578, in _load_model_from_config
    model = instantiate_from_config(c.model)
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 657, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 768, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/modules/encoders/modules.py", line 245, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(
  File "/home/jordancruz/Tools/Blender-Versions/Blender/3.3/python/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1768, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
/home/jordancruz/.config/blender/3.3/scripts/addons/dream_textures/async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

**System (please complete the following information):**
- OS
  - [ ] Windows
  - [ ] macOS
  - [x] Linux
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by carson-katri** [comment]
Please try running the script in the addon at `dream_textures/stable_diffusion/preload_models.py` to download the CLIP model. Version 0.0.6 will perform the equivalent of this on your first generation, so consider updating if you haven’t already.
