### ISSUE TITLE
Generating images don't work on Linux

### ISSUE THREAD

**Issue by owbosh** [carson-katri/dream-textures#17]
Followed all the steps in the add-on tab, including validating the installation. But when trying to generate an image, Blender hangs for a few seconds and then the generation fails.

May be related, but during the installation process, I had to run Blender as root to get the dependencies set up.

This is the error that blender produces:

```
>> Loading model from /home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at /home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=OSError("Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.")>
Traceback (most recent call last):
  File "/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py", line 136, in dream_texture
    generator.load_model()
  File "/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 457, in load_model
    model = self._load_model_from_config(self.config, self.weights)
  File "/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 578, in _load_model_from_config
    model = instantiate_from_config(c.model)
  File "/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 657, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ddpm.py", line 768, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config['target'])(
  File "/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/ldm/modules/encoders/modules.py", line 245, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(
  File "/usr/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1768, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
/home/owbosh/.config/blender/3.3/scripts/addons/dream_textures/async_loop.py:62: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```

**Comment by owbosh** [comment]
Just tried generating while running Blender as root and it works. It would be good to be able to generate images as a regular user...

**Comment by carson-katri** [comment]
You probably only need root while it downloads those models. Subsequent runs should be ok.

**Comment by owbosh** [comment]
It doesn't work as a regular user, the above error always occurs.

**Comment by hammerandtongs** [comment]
This is likely some directories the installation created when run as root, are still root and the user owbosh has no rights to them.

A strategic "chown -R owbosh.owbosh somedirectorysomewhere" might get you sorted.

**Comment by owbosh** [comment]
I chown'd everying inside the dream-textures addon directory. Still the same issue. Is there somewhere else I need to look?

**Comment by pavele11** [comment]
The same issue. I installed plugin as regular user successfully. Then i open Blender folder as root, then open blender executive, and there is no installed plugin. Tried to install plugin in Blender started as root, but stacked at Setup Model Weights step, as this file is already in proper folder, but installation don't finish.  I'm new to Linux, any advice what am i doing wrong?
