### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by NeonThoth** [carson-katri/dream-textures#174]
Traceback (most recent call last):
  File "L:\Steam libary\steamapps\common\Blender\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\mateo\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py", line 36, in <module>
    from .operators.dream_texture import kill_generator
ImportError: cannot import name 'kill_generator' from 'dream_textures.operators.dream_texture' (C:\Users\mateo\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\dream_texture.py)

no idea why im having this issue now the previous version imported fine

**Comment by SolusGod** [comment]
I had the same error. I fixed it by running Blender with Admin Rights and that allowed me to enable the plugin.

**Comment by NeonThoth** [comment]
i fixed the issue a while back forgot to close this but thanks
