### ISSUE TITLE
No idea what to call this bug

### ISSUE THREAD

**Issue by NeonThoth** [carson-katri/dream-textures#183]
Traceback (most recent call last):
  File "C:\Users\mateo\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 344, in prompt2image
    results = generator.generate(
  File "c:\users\mateo\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\base.py", line 70, in generate
    image = make_image(x_T)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\users\mateo\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\users\mateo\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\k_diffusion\sampling.py", line 186, in sample_lms
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\mateo\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 16, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\k_diffusion\external.py", line 100, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\k_diffusion\external.py", line 126, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "c:\users\mateo\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 1440, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\mateo\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 2148, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\mateo\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 798, in forward
    emb = self.time_embed(t_emb)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "L:\Steam libary\steamapps\common\Blender\3.3\python\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float

**Comment by carson-katri** [comment]
Try enabling full precision under advanced configuration.

**Comment by NeonThoth** [comment]
oh wow that actually worked thank you hey while ive got you whats the way to delete old prompts??

**Comment by carson-katri** [comment]
You can’t delete history entries in this version, if that’s what you’re referring to.
