### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by PaintOnBrush** [carson-katri/dream-textures#19]
when i try to generate:

i'm spammed with deprecation warnings:
%appdata%\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loop

here's the log when it fails with the above warnings filtered:
```

>> Loading model from %appdata%\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Model loaded in 6.94s
>> Max VRAM used to load the model: 2.17G
>> Current VRAM usage:2.17G
>> Setting Sampler to k_lms
Generating:   0%|                                                                                | 0/1 [00:00<?, ?it/s]                                                                                      
%appdata%\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: DeprecationWarning: There is no current event loopoundation\Blender\3.3\scripts\addons\dream_textures\async_loop.py:62: Deprecati
  loop = asyncio.get_event_loop()ent 
  loop  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
Generating:   0%|                                                                                | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "%appdata%\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 344, in prompt2image
    results = generator.generate(
  File "%appdata%\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\base.py", line 70, in generate
    image = make_image(x_T)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "%appdata%\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "%appdata%\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\k_diffusion\sampling.py", line 186, in sample_lms
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "%appdata%\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 16, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\k_diffusion\external.py", line 100, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\k_diffusion\external.py", line 126, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "%appdata%\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 1440, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "%appdata%\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 2148, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "%appdata%\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 798, in forward
    emb = self.time_embed(t_emb)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float
>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in
 
0.83s
>>   Max VRAM used for this generation:
 
2.21G.
 
Current VRAM utilization:
 
2.21G
>>   Max VRAM used since script start: 
 
2.21G
```

**Comment by PaintOnBrush** [comment]
also when i enable full precision i get: RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.39 GiB already allocated; 0 bytes free; 3.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

with an nvidia gtx 1650

**Comment by razorx9** [comment]
I also got the same error :
my system spec is:

Nvidia GeForce GTX 1650 4GB with Max-Q Design
Windows 11 Pro - 21H2
intel i7-9750H CPU
8GB RAM
```
>> Loading model from C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Model loaded in 215.03s
>> Max VRAM used to load the model: 2.17G 
>> Current VRAM usage:2.17G
>> Setting Sampler to k_lms


Generating:   0%|                                                                                | 0/1 [00:00<?, ?it/s] 

0%|                                                                                           | 0/25 [00:00<?, ?it/s]

Generating:   0%|                                                                                | 0/1 [00:00<?, ?it/s]


Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 344, in prompt2image
    results = generator.generate(
  File "c:\users\administrator\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\base.py", line 70, in generate
    image = make_image(x_T)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\users\administrator\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\users\administrator\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\k_diffusion\sampling.py", line 186, in sample_lms
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\administrator\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 16, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\k_diffusion\external.py", line 100, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\k_diffusion\external.py", line 126, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "c:\users\administrator\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 1440, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\administrator\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 2148, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\administrator\appdata\roaming\blender foundation\blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 798, in forward
    emb = self.time_embed(t_emb)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\download\softwares\blender-3.3.0-windows-x64\3.3\python\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float
```

**Comment by bandinopla** [comment]
im getting this same error on:

- Windows 10 64bit
- AMD Ryzen 5
- RAM 32GB
- NVidia GeForce 1650 4Gb

**Comment by dasparadoxon** [comment]
yupp I get the same error

**Comment by PaintOnBrush** [comment]
three of four of us confirmed to have the same graphics card.

**Comment by razorx9** [comment]
> 3/4 of us are confirmed to have the same graphics card.
> 
> nvidia 1650
> 
> I was reading on a stabile diffusion site `If your output is a solid green square (known problem on GTX 16xx): Add --precision full --no-half to the launch parameters above, it should look like this: "python scripts/webui.py --precision full --no-half --optimized" Unfortunately, the full precision fix raises ram use drastically so you may may have to moderately reduce your output to 448x448 if on 4gb`

Yep, that seems to be the case, Stable diffusion worked on my system when using the mentioned method.

**Comment by PaintOnBrush** [comment]
the application 'artroom' works for me, although it's not integrated into blender.

**Comment by PaintOnBrush** [comment]
i kept getting the same error something along the lines of "VRAM exceeded ..". This needs the [neonsecret optimized code](https://github.com/basujindal/stable-diffusion/pull/103#issuecomment-1236278620) that removes the variables after use.

**Comment by initiallvisuals** [comment]
same issue with 0.0.6 and blender 3.3.0, but i have a 1660 super OC, run out of cuda memory for anything higher than 128x128 and 15 steps... Might need to wait for that 3090 to drop...

**Comment by pdinklag** [comment]
Same issue as OP here!

- AMD Ryzen 7 3750H
- NVIDIA Geforce GTX 1660 Ti 6GB
- Windows 10

I can also confirm that it works fine with "full precision" enabled.

**Comment by carson-katri** [comment]
There’s no filter. You need 4GB of VRAM minimum, and 1600 cards require full precision enabled due a limitation of that hardware, which uses more ram. So you will most likely need to reduce image size to compensate.

**Comment by bandinopla** [comment]
@carson-katri i have a NVidia GeForce 1650 4Gb, enabled full precition and did a 64x64 res but in my case it crashes and blender closes...

**Comment by reinhix2** [comment]
Same error. NVidia GeForce 1650 4Gb. 4x4 resolution with full precision. Blender closes. Blender don't write anything in crash log.
