### ISSUE TITLE
"RuntimeError: expected scalar type Half but found Float"

### ISSUE THREAD

**Issue by EddyNCNL** [carson-katri/dream-textures#199]
I get the following error when trying to generate an image:

Error: Traceback (most recent call last):
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 344, in prompt2image
    results = generator.generate(
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\base.py", line 70, in generate
    image = make_image(x_T)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\k_diffusion\sampling.py", line 186, in sample_lms
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 16, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\k_diffusion\external.py", line 100, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\k_diffusion\external.py", line 126, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 1440, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 2148, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 798, in forward
    emb = self.time_embed(t_emb)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Eemst\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float

Windows 10
Blender 3.3.0

**Comment by carson-katri** [comment]
Please enable full precision under “Advanced Configuration” for your GPU. If you get a cuda memory error, decrease the image size.

**Comment by EddyNCNL** [comment]
Wow, quick response!
I reduced the image size to 200 x 200, enabled Full Precision.
Now getting below error.

![image](https://user-images.githubusercontent.com/52171063/193111977-231fa2b3-c327-4097-946c-8a0d238e8a40.png)

RuntimeError('CUDA error: out of memory\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.')

**Comment by carson-katri** [comment]
How much VRAM does your GPU have. Looks like it ran out

**Comment by EddyNCNL** [comment]
4 gb dedicated I think.

It looks to spike to 100% when the process stops.

![image](https://user-images.githubusercontent.com/52171063/193114647-06c6c884-ae79-411f-9fb8-052cccd3d80d.png)

Is my card to run it? Or can it be done using CPU only?

**Comment by carson-katri** [comment]
4GB is possible I think, but it will be tricky to get it to run reliably. There’s no option for CPU only at the moment.

**Comment by EddyNCNL** [comment]
Arrr.... me and my low effort GPU!
Well, I guess I'll just have to wait until something else comes along.

Thanks for the quicks responses, good luck further developing this tool.
