### ISSUE TITLE
Error : Process closed unexpectedly

### ISSUE THREAD

**Issue by gnpanimations** [carson-katri/dream-textures#206]
I think i did everything correct but I'm getting an error ( Error : Process closed unexpectedly )

**This is what i found on my blender system console**

Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to C:\Users\karth/.cache\torch\hub\checkpoints\checkpoint_liberty_with_aug.pth
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process.py", line 319, in <module>
    main()
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process.py", line 262, in main
    preload_models()
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process.py", line 250, in preload_models
    import kornia
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\__init__.py", line 10, in <module>
    from . import (
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\augmentation\__init__.py", line 43, in <module>
    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\augmentation\container\__init__.py", line 1, in <module>
    from .augment import AugmentationSequential
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\augmentation\container\augment.py", line 17, in <module>
    from .patch import PatchSequential
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\augmentation\container\patch.py", line 9, in <module>
    from kornia.contrib.extract_patches import extract_tensor_patches
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\contrib\__init__.py", line 4, in <module>
    from .image_stitching import ImageStitcher
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\contrib\image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\feature\__init__.py", line 4, in <module>
    from .integrated import (
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\feature\integrated.py", line 52, in <module>
    class LAFDescriptor(nn.Module):
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\feature\integrated.py", line 65, in LAFDescriptor
    patch_descriptor_module: nn.Module = HardNet(True),
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\kornia\feature\hardnet.py", line 66, in __init__
    pretrained_dict = torch.hub.load_state_dict_from_url(
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\hub.py", line 591, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "C:\Users\karth\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\hub.py", line 457, in download_url_to_file
    u = urlopen(req)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 557, in error
    result = self._call_chain(*args)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
Error: Process closed unexpectedly

**Screenshots**

![Screenshot (13)](https://user-images.githubusercontent.com/71692025/193227712-e53b556e-d397-41fb-b213-2332cc674cf4.png)

**System**
- OS
  - [x] Windows
 
- GPU
  - [x] NVIDIA RTX 2060 12GB

- Addon Version
  - 0.0.6

**Comment by carson-katri** [comment]
Try deleting the folders `huggingface` and `torch` (or `PyTorch`) at `C:\Users\youruser\.cache`
