### ISSUE TITLE
urllib error on Linux while generating images

### ISSUE THREAD

**Issue by crazyrobinhood** [carson-katri/dream-textures#209]
No image is generated inside blender.
All dependencies installed and validation passed.
Restarted blender and OS.

Here is the terminal output:

>> Loading model from /home/nk/.config/blender/3.3/scripts/addons/dream_textures/stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /home/nk/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at /home/nk/.config/blender/3.3/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))>
Traceback (most recent call last):
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/home/nk/bin/blender/candidate/3.3/python/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

**Expected behavior**
Start generating an image.

**System (please complete the following information):**
- OS
  - [x] Pop!_OS 22.04 LTS x86_64
- GPU
  - [x] NVIDIA GeForce GTX 1060 6GB
- Addon Version
  - 0.0.5

**Comment by carson-katri** [comment]
Can you try this solution?
https://github.com/carson-katri/dream-textures/issues/5#issuecomment-1254309733

Also, considering updating to 0.0.6 or the main branch and installing with the instructions under “Contributing” in the readme.

**Comment by crazyrobinhood** [comment]
sudo apt install ca-certificates
sudo update-ca-certificates --fresh
export SSL_CERT_DIR=/etc/ssl/certs

seems to solve the problem on 0.0.5
Now i'm going to try the 0.0.6 update.
thank you!
