### ISSUE TITLE
I get this eroor in the system info in blender

### ISSUE THREAD

**Issue by Surilica** [carson-katri/dream-textures#210]
bpy.context.space_data.system_bookmarks_active = 3
Modules Installed () from 'C:\\Users\\FilipB\\Downloads\\dream_textures-win32-cuda.zip' into 'C:\\Users\\FilipB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_search = "dre"
bpy.ops.stable_diffusion.open_weights_directory()
bpy.ops.stable_diffusion.open_hugging_face()
bpy.ops.stable_diffusion.open_weights_directory()
bpy.context.area.ui_type = 'IMAGE_EDITOR'
bpy.ops.shade.dream_texture()
Traceback (most recent call last):
  File "C:\Users\FilipB\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 344, in prompt2image
    results = generator.generate(
  File "C:\Users\FilipB\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\base.py", line 70, in generate
    image = make_image(x_T)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\FilipB\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\FilipB\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\k_diffusion\sampling.py", line 186, in sample_lms
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\FilipB\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 16, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\k_diffusion\external.py", line 100, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\k_diffusion\external.py", line 126, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\FilipB\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 1440, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\FilipB\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 2148, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\FilipB\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 798, in forward
    emb = self.time_embed(t_emb)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float

**Comment by carson-katri** [comment]
Please enable full precision under “Advanced Configuration” for your GPU

**Comment by Surilica** [comment]
Thanks! <3
