### ISSUE TITLE
MemoryError() after trying to generate anything

### ISSUE THREAD

**Issue by IllianDeCube09** [carson-katri/dream-textures#221]
When I try to generate an image, it starts downloading libraries and at the end gives this error in the console:

> C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\.python_dependencies\torch\cuda\__init__.py:82: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
Error: MemoryError()

And i have CUDA, that's not the problem.

- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by carson-katri** [comment]
What specific GPU do you have

**Comment by IllianDeCube09** [comment]
> What specific GPU do you have

I don't know much about GPU, but I think it is:

Inter(R) HD Graphics 5500

**Comment by carson-katri** [comment]
You need a dedicated NVIDIA GPU to run this.

**Comment by IllianDeCube09** [comment]
Now i ran Blender on NVIDIA GPU and got another error:

> Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\.python_dependencies\transformers\modeling_utils.py", line 392, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\.python_dependencies\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\.python_dependencies\torch\serialization.py", line 1046, in _load
    result = unpickler.load()
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\.python_dependencies\torch\serialization.py", line 1016, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\.python_dependencies\torch\serialization.py", line 997, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch._UntypedStorage).storage()._untyped()
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 16777216 bytes.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\generator_process.py", line 319, in <module>
    main()
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\generator_process.py", line 262, in main
    preload_models()
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\generator_process.py", line 255, in preload_models
    transformers.CLIPTextModel.from_pretrained(clip_version)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\.python_dependencies\transformers\modeling_utils.py", line 1978, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\.python_dependencies\transformers\modeling_utils.py", line 396, in load_state_dict
    if f.read().startswith("version"):
MemoryError
Error: Process closed unexpectedly
