### ISSUE TITLE
super slow and gpu at 0%

### ISSUE THREAD

**Issue by shrek231** [carson-katri/dream-textures#226]
slow and looks like it uses only the cpu

**To Reproduce**
1. Click on full precision because dosnt work without it
2. generate it
**Screenshots**
![image](https://user-images.githubusercontent.com/49622239/193467959-fb9c3ac6-b45a-49f5-a776-2c98996cf420.png)

**System (please complete the following information):**
- OS
  - [x] Windows
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest

**Comment by Official-Husko** [comment]
I can confirm the same issue on my end. Only difference is that i am running and AMD card

**Comment by carson-katri** [comment]
Full precision should not be necessary on the 3050

**Comment by carson-katri** [comment]
@Official-Husko AMD GPUs are not fully supported and will require a manual install at this time

**Comment by shrek231** [comment]
> 

i have tryed to do that but it just gives me an error
![image](https://user-images.githubusercontent.com/49622239/193476251-a1db6502-b3a1-466e-9985-3a49b87e7965.png)
```
C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: Could not find module 'C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")
Error: Traceback (most recent call last):
  File "C:\Users\gavin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 326, in prompt2image
    uc, c = get_uc_and_c(
  File "C:\Users\gavin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\ldm\dream\conditioning.py", line 16, in get_uc_and_c
    uc = model.get_learned_conditioning([''])
  File "C:\Users\gavin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 828, in get_learned_conditioning
    c = self.cond_stage_model.encode(
  File "C:\Users\gavin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\ldm\modules\encoders\modules.py", line 455, in encode
    return self(text, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\gavin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\ldm\modules\encoders\modules.py", line 450, in forward
    z = self.transformer(input_ids=tokens, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\gavin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\ldm\modules\encoders\modules.py", line 420, in transformer_forward
    return self.text_model(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\gavin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\ldm\modules\encoders\modules.py", line 393, in text_encoder_forward
    last_hidden_state = self.encoder(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\gavin\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\ldm\modules\encoders\modules.py", line 320, in encoder_forward
    layer_outputs = encoder_layer(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\transformers\models\clip\modeling_clip.py", line 320, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\modules\normalization.py", line 189, in forward
    return F.layer_norm(
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages\torch\nn\functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

**Comment by ApexxCode** [comment]
I am using the AMD RX 6600 XT and I am also getting the same outcome. CPU can reach over 50%, but GPU will sit at 0%. Is there documentation somewhere how to manually install?

Thanks for this plugin though, seriously!

**Comment by raysintoasttv** [comment]
> @Official-Husko AMD GPUs are not fully supported and will require a manual install at this time

Hey Carson, first off, i really love your work here, very super grateful on all of this. 

Just had a thought, what would help in making a build that would work with AMD gpus? As it is exactly how it looks - i know nothing about compiling or coding. Is it that you need the hardware for the code to compile with or is it possible to compile your current machine (i think you mentioned you dont have an AMD gpu) and have someone test it?
