### ISSUE TITLE
Traceback (most recent call last):   File "D:\Blender\3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable

### ISSUE THREAD

**Issue by ax53** [carson-katri/dream-textures#247]
Tried the 0.6 and followed installation instructions but I get this error when activating the addon.

Windows 10 on a 64bit system.
Blender 3.3

```
Traceback (most recent call last):
  File "D:\Blender\3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Per\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py", line 33, in <module>
    from .operators.open_latest_version import check_for_updates
  File "C:\Users\Per\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\open_latest_version.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by carson-katri** [comment]
Hmm, you may need to reinstall blender, requests should be included in the Blender installation afaik.

**Comment by ax53** [comment]
Maybe it's because I use a portable blender version. I will try the installer. Thanks!
