### ISSUE TITLE
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by namelessh8u** [carson-katri/dream-textures#255]
- OS
  - Windows 11
- GPU
  - NVIDIA GTX 1060 3GB
- Addon Version
  - 0.0.6

Error: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 344, in prompt2image
    results = generator.generate(
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\base.py", line 70, in generate
    image = make_image(x_T)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\dream\generator\txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\k_diffusion\sampling.py", line 186, in sample_lms
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 16, in forward
    uncond, cond = self.inner_model(x_in, sigma_in, cond=cond_in).chunk(2)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\k_diffusion\external.py", line 100, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\k_diffusion\external.py", line 126, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 1440, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ddpm.py", line 2148, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 806, in forward
    h = module(h, emb, context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\stable_diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 90, in forward
    x = layer(x)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

**Comment by NullSenseStudio** [comment]
I'm not very sure but this could be caused by outdated graphics card drivers.

Unrelated to this error however is 3GB of VRAM is not going to be able to work.
