### ISSUE TITLE
Can no longer activate the addon after installing

### ISSUE THREAD

**Issue by olliebarbs** [carson-katri/dream-textures#27]
I previously managed to install the addon (v0.04) however had trouble verifying the update. I decided to reinstall dependencies and then to reinstall addon fully, however when activating addon (tested with 0.04 and 0.05) I get 

`Exception in module register(): C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py", line 51, in register
    async_loop.setup_asyncio_executor()
NameError: name 'async_loop' is not defined
`

I tried this on a fresh install of Blender 3.3 with the same result.

I'm using Windows 11

**Comment by olliebarbs** [comment]
Re loading the addon and re enabling i seem to get this error once too. 

`reloading addon: dream_textures 1663543920.880767 1663543986.5752223 'C:\\Users\\Ollie\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\dream_textures\\__init__.py'
Exception in module register(): C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py", line 71, in register
    importlib.import_module("transformers")
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\transformers\utils\__init__.py", line 33, in <module>
    from .generic import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\transformers\utils\generic.py", line 28, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\transformers\utils\import_utils.py", line 111, in <module>
    _ = importlib_metadata.version("datasets")
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\importlib\metadata\__init__.py", line 955, in version
    return distribution(distribution_name).version
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\importlib\metadata\__init__.py", line 928, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\importlib\metadata\__init__.py", line 514, in from_name
    dist = next(iter(dists), None)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\importlib\metadata\__init__.py", line 874, in <genexpr>
    return itertools.chain.from_iterable(
TypeError: unhashable type: 'list'`


If I then try to enable again, I get the first error

**Comment by carson-katri** [comment]
Closing as stale due to many changes since this issue was posted. If you're still experiencing issues, feel free to re-open this.
