### ISSUE TITLE
new version not working

### ISSUE THREAD

**Issue by eliecer696** [carson-katri/dream-textures#278]
when I try to run the the dream addon i get this error in the logg

ImportError('Failed to load PyTorch C extensions:\n    It appears that PyTorch has loaded the `torch/_C` folder\n    of the PyTorch repository rather than the C extensions which\n    are expected in the `torch._C` namespace. This can occur when\n    using the `install` workflow. e.g.\n        $ python setup.py install && python -c "import torch"\n\n    This error can generally be solved using the `develop` workflow\n        $ python setup.py develop && python -c "import torch"  # This should succeed\n    or by running Python from a different directory.')
 
i have try in multiple pc but the error is all ways the same 

blender version 3.3.0 -3.3.1-3.4-3.4.1
- OS
  - [x] Windows 11-10
  - [ ] macOS
  - [ ] Other
- GPU
  - [x] NVIDIA
  - [ ] NVIDIA 16*XX*
  - [ ] Apple Silicon
  - [ ] AMD
- Addon Version
  - Latest
  -

**Comment by carson-katri** [comment]
Which version did you have before? Also, which file did you download from the release?

**Comment by MetaAleks** [comment]
On Win 11 RTX 3050 my error looks like this:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Mriya Reality Labs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py", line 30, in <module>
    from .render_pass import register_render_pass, unregister_render_pass
  File "C:\Users\Mriya Reality Labs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\render_pass.py", line 8, in <module>
    from .operators.dream_texture import dream_texture
  File "C:\Users\Mriya Reality Labs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\dream_texture.py", line 7, in <module>
    from ..preferences import StableDiffusionPreferences
  File "C:\Users\Mriya Reality Labs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\preferences.py", line 11, in <module>
    from .property_groups.dream_prompt import DreamPrompt
  File "C:\Users\Mriya Reality Labs\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\property_groups\dream_prompt.py", line 3, in <module>
    from ..prompt_engineering import *
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

**Comment by carson-katri** [comment]
Simply restarting blender before enabling the addon should fix tbag

**Comment by eliecer696** [comment]
> 



> 

i try installing 5 but it alose gives me an error

**Comment by eliecer696** [comment]
> 

restarting before enableing still din't work

**Comment by marharols** [comment]
Had the exact same error, for me the issue was that i had downloaded the arm version (which i am pretty sure is not for windows). Downloaded the cuda version, everything worked smoothly.

**Comment by eliecer696** [comment]
> everything

seems to work thanks man is just the 32 bit version threw me off
