### ISSUE TITLE
Scene is `None` before Image to Image completes

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#29]
Not sure why but I always get this StructRNA error message when using Initial Image option. Was hoping for it to generate image from image. And wondering whether inpainting really works... So far no luck.

```
>> image will be resized to fit inside a box 512x512 in size.
>> after adjusting image dimensions to be multiples of 64, init image is 512x512
>> sampler 'KSampler' is not yet supported. Using DDIM sampler
2022-09-19 12:01:23,448 [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at /Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=ReferenceError('StructRNA of type Scene has been removed')>
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/operators/dream_texture.py", line 246, in dream_texture
    await loop.run_in_executor(None, perform)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/operators/dream_texture.py", line 209, in perform
    generator.prompt2image(
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/stable_diffusion/ldm/generate.py", line 344, in prompt2image
    results = generator.generate(
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/stable_diffusion/ldm/dream/generator/base.py", line 70, in generate
    image = make_image(x_T)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/stable_diffusion/ldm/dream/generator/txt2img.py", line 30, in make_image
    samples, _ = sampler.sample(
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ksampler.py", line 83, in sample
    K.sampling.__dict__[f'sample_{self.schedule}'](
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/site-packages/k_diffusion/sampling.py", line 193, in sample_lms
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/stable_diffusion/ldm/models/diffusion/ksampler.py", line 66, in route_callback
    img_callback(k_callback_values['x'], k_callback_values['i'])
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/operators/dream_texture.py", line 167, in view_step
    step_image = pil_to_image(generator._sample_to_image(samples), name=f'Step {step + 1}/{scene.dream_textures_prompt.steps}')
ReferenceError: StructRNA of type Scene has been removed
Generating:   0%|                                                                                                                          | 0/1 [00:00<?, ?it/s]Running DDIM Sampling with 7 timesteps

Decoding image:   0%|                                                                                                                      | 0/7 [00:00<?, ?it/s]
```

**Comment by enzyme69** [comment]
Occasionally the error message is also different, this is when I want to use "Initial Image" but also specify photograph.

```
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using slower but more accurate full-precision math (--full_precision)
>> Model loaded in 118.59s
>> Setting Sampler to k_lms
2022-09-19 12:19:19,541 [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='Task-3' coro=<DreamTexture.dream_texture() done, defined at /Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/operators/dream_texture.py:105> exception=AttributeError('Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting ImageFormatSettings.file_format')>
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/operators/dream_texture.py", line 246, in dream_texture
    await loop.run_in_executor(None, perform)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/operators/dream_texture.py", line 207, in perform
    init_img_path = save_temp_image(init_img)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.4/scripts/addons/dream_textures/operators/dream_texture.py", line 191, in save_temp_image
    settings.file_format = file_format
AttributeError: Writing to ID classes in this context is not allowed: Scene, Scene datablock, error setting ImageFormatSettings.file_format
```

**Comment by enzyme69** [comment]
Maybe I should set the Edit Image into "Paint Mode" or something...

**Comment by enzyme69** [comment]
Usually the error is after I did a process and re-running it from the same window. The workaround this for now is to recall prompt. But I wonder why it gives such error.

**Comment by carson-katri** [comment]
Looks like a bug with the scene object no longer being available. I will investigate.

**Comment by carson-katri** [comment]
Can you verify if this is still broken in 0.0.7?
