### ISSUE TITLE
Error: OSError(22, 'The specified module could not be found.', None, 126) When generating

### ISSUE THREAD

**Issue by GiyomuWeb** [carson-katri/dream-textures#293]
This is the error I get, I just installed the module, following all the steps in blender. I have the "addon Setup Complete" checkmark and everything.

Error: OSError(22, 'The specified module could not be found.', None, 126)

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\generator_process.py", line 240, in main
    from stable_diffusion.ldm.generate import Generate
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 7, in <module>
    import torch
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\.python_dependencies\torch\__init__.py", line 137, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\.python_dependencies\torch\lib\torch_python.dll" or one of its dependencies.

**Comment by GiyomuWeb** [comment]
Oh... yeah... My bad, I had the latest Blender installed but my shortcut was still for the previous version. Launched the latest and it worked. My bad. I didn't know Blender didn't automatically delete the previous version when updating.
