### ISSUE TITLE
Problems with cycles render pass

### ISSUE THREAD

**Issue by timmyL17** [carson-katri/dream-textures#298]
I am able to run dream-textures correctly using the image generation instructions. I can also specify an initial image (512x512) in that pane, and img2img works well. But if I follow the render pass instructions (again with the render output set to 512x512), I get the following errors in the console. I am on ArchLinux with an nvidia RTX 2080 Ti, which I know is not officially supported. But it is confusing why img2img works fine from the prompt but not when run on the render pass. Any ideas? Thanks!

`Traceback (most recent call last):
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/operators/dream_texture.py", line 137, in modal
    raise e
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/operators/dream_texture.py", line 131, in modal
    next(generator_advance)
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/generator_process.py", line 99, in prompt2image
    callbacks[action](**tup[1])
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/operators/dream_texture.py", line 223, in image_callback
    headless_image_callback(shared_memory_name, seed, width, height, upscaled)
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/render_pass.py", line 58, in image_callback
    shared_memory.close()
  File "/usr/lib/python3.10/multiprocessing/shared_memory.py", line 227, in close
    self._mmap.close()
BufferError: cannot close exported pointers exist
Error: Python: Traceback (most recent call last):
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/operators/dream_texture.py", line 137, in modal
    raise e
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/operators/dream_texture.py", line 131, in modal
    next(generator_advance)
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/generator_process.py", line 99, in prompt2image
    callbacks[action](**tup[1])
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/operators/dream_texture.py", line 223, in image_callback
    headless_image_callback(shared_memory_name, seed, width, height, upscaled)
  File "/home/tlangloi/.config/blender/3.3/scripts/addons/dream-textures/render_pass.py", line 58, in image_callback
    shared_memory.close()
  File "/usr/lib/python3.10/multiprocessing/shared_memory.py", line 227, in close
    self._mmap.close()
BufferError: cannot close exported pointers exist
`

**Comment by timmyL17** [comment]
I get the same errors if I use the 0.0.7 release, or the current main branch.

**Comment by timmyL17** [comment]
I think this just has to do with pointers still existing when trying to close the shared memory buffer. If I add

`
del pixels
del reshaped
`
At line 58 of `render_pass.py`, the problem seems to go away. I'm not sure if that's the correct way to fix it though, and why others are not seeing this problem as well.

**Comment by carson-katri** [comment]
Maybe because they’re views into the data and not copies it needs to be deleted manually before closing so it doesn’t try to read it afterward?

**Comment by timmyL17** [comment]
That's what it seems like. I'm not sure why others haven't seen it, maybe because I'm on linux. Created a PR.
