### ISSUE TITLE
PermissionError: [WinError 5]

### ISSUE THREAD

**Issue by JoukoSalonen** [carson-katri/dream-textures#31]
hi!
I'm getting this error message, any advice how to get over it?

PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Blender Foundation\\Blender 3.2\\3.2\\python\\Include'

*this it what is above it
Error: Python: Traceback (most recent call last):
  File "C:\Users\jouko\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\operators\install_dependencies.py", line 141, in execute
    install_and_import_requirements(requirements_txt=context.scene.dream_textures_requirements_path)
  File "C:\Users\jouko\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\operators\install_dependencies.py", line 115, in install_and_import_requirements
    python_devel_tgz.extractall(path=python_include_dir, members=members(python_devel_tgz))
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\tarfile.py", line 2040, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\tarfile.py", line 2081, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\tarfile.py", line 2146, in _extract_member
    os.makedirs(upperdirs)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Blender Foundation\\Blender 3.2\\3.2\\python\\Include'

**Comment by TakUser** [comment]
Same problem with the addon.  Interested in an answer for a fix.

**Comment by PaintOnBrush** [comment]
i ran blender as admin to fix this.

**Comment by JoukoSalonen** [comment]
ok, thx. I thought I had admin rights but ok, I'll try to fix it and report here if succeed, Thank you!!

**Comment by Brettehwarrior** [comment]
Can confirm restarting blender as admin fixed this for me

**Comment by carson-katri** [comment]
Dependency installation is no longer required in the latest versions.
