### ISSUE TITLE
Windows + RX580

### ISSUE THREAD

**Issue by maddoglv** [carson-katri/dream-textures#349]
The installation and validation is OK, but when I restart and generate the image.
I suppose it wants to use the CPU I have AMD A10-7850k (integrated GPU disabled)

The Inputs
![image](https://user-images.githubusercontent.com/36969329/197644763-ffd4c05b-b54f-4668-91d6-b37813bd22a9.png)

>> Loading model from C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\stable_diffusion/models/ldm/stable-diffusion-v1/model.ckpt
>> Calculating sha256 hash of weights file
>> sha256 = fe4efff1e174c627256e44ec2991ba279b3816e364b49f9be2abc0b3ff3f8556 (14.84s)
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
>> Using half precision math. Call with --full_precision to use more accurate but VRAM-intensive full precision.
>> Model loaded in 68.30s
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<DreamTexture.dream_texture() done, defined at C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\operators\dream_texture.py:105> exception=RuntimeError('"log" "_vml_cpu" not implemented for \'Half\'')>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\operators\dream_texture.py", line 136, in dream_texture
    generator.load_model()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 470, in load_model
    self._set_sampler()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dream_textures\stable_diffusion\ldm\generate.py", line 551, in _set_sampler
    self.sampler = KSampler(self.model, 'lms', device=self.device)
  File "c:\users\User\appdata\roaming\blender foundation\blender\3.0\scripts\addons\dream_textures\stable_diffusion\ldm\models\diffusion\ksampler.py", line 23, in __init__
    self.model = K.external.CompVisDenoiser(model)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\k_diffusion\external.py", line 137, in __init__
    super().__init__(model, model.alphas_cumprod, quantize=quantize)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\k_diffusion\external.py", line 94, in __init__
    super().__init__(((1 - alphas_cumprod) / alphas_cumprod) ** 0.5, quantize)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\site-packages\k_diffusion\external.py", line 48, in __init__
    self.register_buffer('log_sigmas', sigmas.log())
RuntimeError: "log" "_vml_cpu" not implemented for 'Half'

**Comment by carson-katri** [comment]
You are running an old version of the addon, please update to 0.0.7: https://github.com/carson-katri/dream-textures/releases/tag/0.0.7
Follow the instructions under "Windows Installation" to get up and running.
