### ISSUE TITLE
Render Pass Dream crashes Blender

### ISSUE THREAD

**Issue by enzyme69** [carson-katri/dream-textures#364]
### Description

No idea what happened, but I did change around the compositor node during processing render.

```
Exception ignored in: <function CyclesRender.__del__ at 0x11f662d40>
Traceback (most recent call last):
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/scripts/addons/cycles/__init__.py", line 54, in __del__
    engine.free(self)
  File "/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/scripts/addons/cycles/engine.py", line 79, in free
    if hasattr(engine, "session"):
ReferenceError: StructRNA of type CyclesRender has been removed
Writing: /var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/makeseamless_003.crash.txt
zsh: segmentation fault  /Applications/BLENDER_34/Blender.app/Contents/MacOS/Blender

Saving session.../Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

```

### Steps to Reproduce

Render using Dream Texture render pass...

### Expected Behavior

It should just give the dream output.

### Addon Version

macOS (Apple Silicon)

### GPU

Apple Silicon

**Comment by enzyme69** [comment]
Getting this error quite often:
```
/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/Applications/BLENDER_34/Blender.app/Contents/Resources/3.4/python/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
