### ISSUE TITLE
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

### ISSUE THREAD

**Issue by TheConceptBoy** [carson-katri/dream-textures#372]
### Description

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\DevStationEisenstadt\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py", line 30, in <module>
    from .render_pass import register_render_pass, unregister_render_pass
  File "C:\Users\DevStationEisenstadt\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\render_pass.py", line 8, in <module>
    from .operators.dream_texture import dream_texture
  File "C:\Users\DevStationEisenstadt\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\dream_texture.py", line 7, in <module>
    from ..preferences import StableDiffusionPreferences
  File "C:\Users\DevStationEisenstadt\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\preferences.py", line 11, in <module>
    from .property_groups.dream_prompt import DreamPrompt
  File "C:\Users\DevStationEisenstadt\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\property_groups\dream_prompt.py", line 3, in <module>
    from ..prompt_engineering import *
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

`

### Steps to Reproduce

Blender 3.3.1
This library release 0.0.7
Attempt to enable the plugin via the checkbox in blender add-ons window.

### Expected Behavior

Plugin should get enabled.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
You most likely need to simply restart Blender then try activating it again. You may also want to update to 0.0.8.

**Comment by TheConceptBoy** [comment]
> You most likely need to simply restart Blender then try activating it again. You may also want to update to 0.0.8.

Updated to 0.0.8. Same error persists. This is a new installation of Windows btw (hard drive upgrade) so it's a fresh OS. Error happens when I toggle on the plugin to enable in the properties addons window.

![image](https://user-images.githubusercontent.com/52581279/201352937-ae228efe-41fb-450f-90e0-029f4ab72ec4.png)

**Comment by carson-katri** [comment]
You could try decompressing it manually into `C:\Users\youruser\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons`

**Comment by TheConceptBoy** [comment]
Oh yeah, that worked. So perhaps the initialization method has something in it. 

Other than that, there's even less work involved getting this plugin up and running. nice work.

**Comment by coffeebuyer** [comment]
> 

This worked for me also when I had the same error just now today

**Comment by serhiro89** [comment]
In the addon settings, when loading download Stable Diffusion v 2.1 (Recommended) nothing happens, does not start the download, selected all as required by the instructions
