### ISSUE TITLE
line 440, in __getitem__     return cls._member_map_[name]

### ISSUE THREAD

**Issue by satyajitghana** [carson-katri/dream-textures#426]
### Description

```
pipeline'
Traceback (most recent call last):
  File "/home/satyajit/.config/blender/3.2/scripts/addons/dream-textures/operators/project.py", line 53, in draw
    if Pipeline[context.scene.dream_textures_project_prompt.pipeline].model():
  File "/home/satyajit/Downloads/blender-3.2.1-linux-x64/3.2/python/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: ''
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1333 pyrna_enum_to_py: current value '2' matches no enum in 'DreamPrompt', '', 'pipeline'
Traceback (most recent call last):
  File "/home/satyajit/.config/blender/3.2/scripts/addons/dream-textures/ui/panels/dream_texture.py", line 113, in draw
    if Pipeline[get_prompt(context).pipeline].seamless():
  File "/home/satyajit/Downloads/blender-3.2.1-linux-x64/3.2/python/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: ''
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1333 pyrna_enum_to_py: current value '2' matches no enum in 'DreamPrompt', '', 'pipeline'
Traceback (most recent call last):
  File "/home/satyajit/.config/blender/3.2/scripts/addons/dream-textures/ui/panels/dream_texture.py", line 127, in poll
    return get_prompt(context).prompt_structure != file_batch_structure.id and Pipeline[get_prompt(context).pipeline].negative_prompts()
  File "/home/satyajit/Downloads/blender-3.2.1-linux-x64/3.2/python/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: ''
```

### Steps to Reproduce

1. Clone the repository
2. Install deps using using blender addon prefs
3. Run with Project Dream Texture

Blender 3.2
Python 3.10
Ubuntu 20.04

### Expected Behavior

It should project texture

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by barshag** [comment]
same for me

**Comment by jedStevens** [comment]
same here

**Comment by mmalahe** [comment]
+1

**Comment by hanaishi** [comment]
Me too!
