### ISSUE TITLE
When trying to upscale, I get AttributeError: 'str' object has no attribute '__array_interface__' in Blender 3.5

### ISSUE THREAD

**Issue by Lissanro** [carson-katri/dream-textures#445]
### Description

Here is full console log of what happens when I try to upscale. I deleted upscale version of SD to let it download again, but the error remained.

```
Read prefs: Z:\home\lissanro\.config\blender\3.5\config\userpref.blend
Reloading external rigs...
Reloading external metarigs...
Read blend: z:\tmp\Test.blend
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 485/485 [00:00<00:00, 242kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 151kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 348/348 [00:00<00:00, 174kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 634/634 [00:00<00:00, 425kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 681M/681M [13:00<00:00, 872kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████| 525k/525k [00:01<00:00, 360kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 460/460 [00:00<00:00, 455kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 825/825 [00:00<00:00, 550kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:02<00:00, 406kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 977/977 [00:00<00:00, 652kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 982/982 [00:00<00:00, 992kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 947M/947M [15:18<00:00, 1.03MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 558/558 [00:00<00:00, 373kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 111M/111M [01:05<00:00, 1.70MB/s]
Fetching 14 files: 100%|██████████████████████████████████████████████████████████████| 14/14 [29:50<00:00, 127.90s/it]
Exception: Traceback (most recent call last):
  File "Z:\home\lissanro\.config\blender\3.5\scripts\addons\dream_textures\generator_process\actor.py", line 273, in _receive
    for res in iter(response):
  File "Z:\home\lissanro\.config\blender\3.5\scripts\addons\dream_textures\generator_process\actions\upscale.py", line 52, in upscale
    low_res_image = Image.fromarray(image)
  File "\\server\share\home\lissanro\.config\blender\3.5\scripts\addons\dream_textures\.python_dependencies\PIL\Image.py", line 2982, in fromarray
    arr = obj.__array_interface__
AttributeError: 'str' object has no attribute '__array_interface__'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Z:\home\lissanro\.config\blender\3.5\scripts\addons\dream_textures\generator_process\actor.py", line 111, in run_callbacks
    done_callback(self)
  File "Z:\home\lissanro\.config\blender\3.5\scripts\addons\dream_textures\operators\upscale.py", line 114, in image_done
    tile: ImageUpscaleResult = future.result()
  File "Z:\home\lissanro\.config\blender\3.5\scripts\addons\dream_textures\generator_process\actor.py", line 58, in result
    raise self._exception
AttributeError: 'str' object has no attribute '__array_interface__'
```

### Steps to Reproduce

1. Install Blender 3.5 from https://builder.blender.org/download/daily/
2. Install the addon
3. Generate a texture
4. Try to upscale it

### Expected Behavior

I expected to get upscaled texture.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA RTX 2060 SUPER 8GB

**Comment by Lissanro** [comment]
I was trying available patches in pull requests, and I noticed that after applying https://github.com/carson-katri/dream-textures/pull/410 this issue was solved.
