### ISSUE TITLE
Receiving error when attempting to enable addon - Blender 3.4

### ISSUE THREAD

**Issue by vaporization** [carson-katri/dream-textures#454]
### Description

Attempting to install latest release package on Blender 3.4, receiving error when attempting to enable addon.

### Steps to Reproduce

Attempt to install latest release package on Blender 3.4.

### Expected Behavior

Error produced:
```
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\saweb\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\__init__.py", line 36, in <module>
    from .render_pass import register_render_pass, unregister_render_pass
  File "C:\Users\saweb\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\render_pass.py", line 12, in <module>
    from .operators.dream_texture import dream_texture, weights_are_installed
  File "C:\Users\saweb\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 7, in <module>
    from ..property_groups.dream_prompt import backend_options
  File "C:\Users\saweb\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\property_groups\dream_prompt.py", line 6, in <module>
    from ..prompt_engineering import *
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'


```

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by polarsky89** [comment]
Worked for me when copied 'dream_textures.prompt_engineering' file manualy

**Comment by M-HassanTariq** [comment]
> Worked for me when copied 'dream_textures.prompt_engineering' file manualy

At what stage do you manually copy that file. It simply gives this error when you install the addon

**Comment by slowshutterfilms** [comment]
> > Worked for me when copied 'dream_textures.prompt_engineering' file manualy
> 
> At what stage do you manually copy that file. It simply gives this error when you install the addon

It seems blender isn't importing all the files when installing. What worked for me is to install the addon, then copy and paste all the contents of the zip file to the plugin location, then finally enable the addon

**Comment by abhollow** [comment]
> > > Worked for me when copied 'dream_textures.prompt_engineering' file manualy
> > 
> > 
> > At what stage do you manually copy that file. It simply gives this error when you install the addon
> 
> It seems blender isn't importing all the files when installing. What worked for me is to install the addon, then copy and paste all the contents of the zip file to the plugin location, then finally enable the addon

This also worked for me.  It somehow didn't import a staggering amount of files, not just the engineering module.

**Comment by SolacianAllie** [comment]
i also got this error, ive noticed for me its when i use dream textures on any drive but C drive, which was hard enough getting it to even do that, spent about an hour trying to make blender actually install on my D drive, even after setting it up, but i got it working then encountered this

**Comment by Kirthi-2000** [comment]
Traceback (most recent call last):
 
File "C:\Program Files\Blender Foundation\Blender 3.613.6\scripts\modules\[addon_utils.py](http://addon_utils.py/)", line 333, in enable mad import_(module_name)
 
File "C:\Program Files\Blender Foundation\Blender 3.613.6\scripts\addons\verge3d_init__.py", line 56, in <module> from pluginUtils.log import printLog
 
ModuleNotFoundError: No module named 'pluginUtils'
