### ISSUE TITLE
on blender 3.3.1 and 3.4 i get this error that stops dream textures working OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by ringusd** [carson-katri/dream-textures#457]
### Description

Python: Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\dream_texture.py", line 159, in modal
    raise e
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\dream_texture.py", line 153, in modal
    next(generator_advance)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\block_in_use.py", line 10, in sub
    yield from func(self, *args, **kwargs)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\intents\prompt_to_image.py", line 11, in prompt2image
    self.send_intent(Intent.PROMPT_TO_IMAGE, **args)
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\__init__.py", line 100, in send_intent
    stdin.flush()
OSError: [Errno 22] Invalid argument

### Steps to Reproduce

press generate in dream textures addon always gives the same error as in description
in both blender 3.3.1 and 3.4, addon says its installed ok in both blender versions

### Expected Behavior

expect dream textures to work but gives error
OSError: [Errno 22] Invalid argument

### Addon Version
dream textures version 0.08 from 
https://blendermarket.com/products/dream-textures
imported model weight sd-v1-4.ckpt

Windows (CUDA)

### GPU

NVIDIA

**Comment by JasonHoku** [comment]
'dream textures version 0.08'
Any reason why you're not on 0.09 yet?

Did you run both installation and setup as admin like instructed? Personally I set the properties of blender to always run as admin.

Things seem to be working now with an automated model installation process in 0.09 so you may find success or more clues to what could be going wrong by looking for solutions in there.
