### ISSUE TITLE
Can not install add on on Blender 3.3.1 Error Traceback (most recent call last) v0.0.9

### ISSUE THREAD

**Issue by PooyaDeperson** [carson-katri/dream-textures#464]
### Description

Can not install add on v0.0.9 on Blender 3.3.1 Error Traceback (most recent call last) 
--
Info Log:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\DepersonStation\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\__init__.py", line 40, in <module>
    from .prompt_engineering import *
ModuleNotFoundError: No module named 'dream_textures.prompt_engineering'

![image](https://user-images.githubusercontent.com/29626054/208889138-6fa7362c-d959-450e-8726-d3440bb7a985.png)

### Steps to Reproduce

Unzpip the .7z
install addon using blender > preferences > addon

### Expected Behavior

add on installation.

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by PooyaDeperson** [comment]
Solution
Blender may have missed some files when installing the addon from the ZIP. Here’s what you can try:
1. Delete the dream textures folder here C: \Users\YOUR_USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures
2. Manually unzip the add-on folder to that same path. After doing that there should be a file __init__.py in C: \Users\YOUR_USER\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\__init__.py

Then restart Blender and see if the problem persists.
