### ISSUE TITLE
libcudnn.so.8: cannot open shared object file (but only in rendering composite)

### ISSUE THREAD

**Issue by TutajITeraz** [carson-katri/dream-textures#475]
### Description

On my linux machine blender, hangs at "Generating... and  throws an error:

```
/home/lukasz/.config/blender/3.3/scripts/addons/dream-textures/generator_process/actor.py:300: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if response == Message.END:
The config attributes {'depth_estimator': ['transformers', 'DPTForDepthEstimation']} were passed to GeneratorPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
Keyword arguments {'depth_estimator': ['transformers', 'DPTForDepthEstimation']} are not expected by GeneratorPipeline and will be ignored.
You have disabled the safety checker for <class 'dream-textures.generator_process.actions.image_to_image.image_to_image.<locals>.GeneratorPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Exception in thread Thread-3 (_send_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lukasz/.config/blender/3.3/scripts/addons/dream-textures/generator_process/actor.py", line 299, in _send_thread
    response = self._response_queue.get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/usr/lib/python3.10/site-packages/torch-1.13.0-py3.10-linux-x86_64.egg/torch/__init__.py", line 191, in <module>
    _load_global_deps()
  File "/usr/lib/python3.10/site-packages/torch-1.13.0-py3.10-linux-x86_64.egg/torch/__init__.py", line 153, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudnn.so.8: cannot open shared object file: No such file or directory

```

Maybe it is simmilar problem to the
https://github.com/carson-katri/dream-textures/issues/430#issuecomment-1355921816 
?

Generating textures works fine, so cuda works well.

### Steps to Reproduce

1. Connect Compositing Dream Textures to Composite node
2. Press F12 to render

### Expected Behavior

AI generated render should show up.

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by NullSenseStudio** [comment]
I think this is likely caused by you running out of VRAM. The frontend is attempting to unpickle a torch object which wouldn't normally happen unless an error is raised, like `torch.cuda.OutOfMemoryError`. Now normally that would lead to `ModuleNotFoundError: No module named 'torch'`, but seems the frontend was able to locate and attempt to load a torch package.

Can you get this same error to occur if you try generating an extremely large image like 2048x2048?

You may have to try some different memory optimizations or do your cycles rendering on CPU.

**Comment by TutajITeraz** [comment]
I'll try that when I get home.  it's weird because I currently render textures at 768x768 and render composition node at 1280x768 but automatic1111 had no problems even at 1536x768 on my RTX 3060 12GB.

**Comment by TutajITeraz** [comment]
It works for 512x512, and also 768x768, and 1280x768 but only for the stable-diffustion-2-depth model with Depth input passed.

2048x2048 results with an error like above, as you expected.

So the real problem was with the model i was trying to use. I want to use color data for styling rendering, so i have downloaded a new model (from the plugin preferences using hugging face token).

Now, with the stabilityai/stable-diffusion-2-1 and color input and 512x512 resolution I'am experiencing different problem:

```
/home/lukasz/.config/blender/3.3/scripts/addons/dream-textures/generator_process/actor.py:300: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if response == Message.END:
Exception: Traceback (most recent call last):
  File "/home/lukasz/.config/blender/3.3/scripts/addons/dream-textures/generator_process/actor.py", line 273, in _receive
    for res in iter(response):
  File "/home/lukasz/.config/blender/3.3/scripts/addons/dream-textures/generator_process/actions/image_to_image.py", line 191, in image_to_image
    pipe = GeneratorPipeline.from_pretrained(
  File "/home/lukasz/Developer/dream-textures/.python_dependencies/diffusers/pipeline_utils.py", line 708, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/lukasz/Developer/dream-textures/.python_dependencies/diffusers/modeling_utils.py", line 452, in from_pretrained
    model_file = cls._get_model_file(
  File "/home/lukasz/Developer/dream-textures/.python_dependencies/diffusers/modeling_utils.py", line 593, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory /home/lukasz/.cache/huggingface/diffusers/models--stabilityai--stable-diffusion-2-1/snapshots/36a01dc742066de2e8c91e7cf0b8f6b53ef53da1/vae.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lukasz/.config/blender/3.3/scripts/addons/dream-textures/generator_process/actor.py", line 111, in run_callbacks
    done_callback(self)
  File "/home/lukasz/.config/blender/3.3/scripts/addons/dream-textures/render_pass.py", line 147, in on_done
    result = future.result()
  File "/home/lukasz/.config/blender/3.3/scripts/addons/dream-textures/generator_process/actor.py", line 58, in result
    raise self._exception
OSError: Error no file named diffusion_pytorch_model.bin found in directory /home/lukasz/.cache/huggingface/diffusers/models--stabilityai--stable-diffusion-2-1/snapshots/36a01dc742066de2e8c91e7cf0b8f6b53ef53da1/vae.
```
