### ISSUE TITLE
Negative Prompt Broken In dream_textures.py (on 279f163)

### ISSUE THREAD

**Issue by JasonHoku** [carson-katri/dream-textures#524]
### Description

Adding a negative prompt in the Image Editor Dream Textures results in the following error:

```
Exception: Traceback (most recent call last):
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 273, in _receive
    for res in iter(response):
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 527, in prompt_to_image
    yield from pipe(
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 419, in __call__
    text_embeddings = self._encode_prompt(
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 282, in _encode_prompt
    raise TypeError(
TypeError: `negative_prompt` should be the same type to `prompt`, but got <class 'str'> != <class 'list'>.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 98, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\JasonHoku\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 145, in exception_callback
    raise exception
TypeError: `negative_prompt` should be the same type to `prompt`, but got <class 'str'> != <class 'list'>.
```

### Steps to Reproduce

Add a negative prompt to Image Editor and gen

### Expected Behavior

not crash

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by PredellaN** [comment]
experiencing the same issue (using today's master branch)

**Comment by NullSenseStudio** [comment]
Most likely caused by #486. Should require changes similar here: https://github.com/carson-katri/dream-textures/blob/7aa84992e1834a78fb8d681bf2b63713b87d61b5/operators/dream_texture.py#L150-L158
