### ISSUE TITLE
JSON Export broken in 0.0.9

### ISSUE THREAD

**Issue by GottfriedHofmann** [carson-katri/dream-textures#526]
### Description

When exporting a promt from history to JSON, I get the following error:

Traceback (most recent call last):
  File "C:\Users\g\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\view_history.py", line 121, in execute
    json.dump(args, target, indent=4)
  File "C:\Users\g\Desktop\blender-3.4.1-windows-x64\3.4\python\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\g\Desktop\blender-3.4.1-windows-x64\3.4\python\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\g\Desktop\blender-3.4.1-windows-x64\3.4\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\g\Desktop\blender-3.4.1-windows-x64\3.4\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\g\Desktop\blender-3.4.1-windows-x64\3.4\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Scheduler is not JSON serializable

### Steps to Reproduce

Create an image in Deram Textures
Export the promt by clicking the botton "Export promt" that runs bpy.ops.shade.dream_textures_history_export()

### Expected Behavior

Store the JSON

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by GottfriedHofmann** [comment]
I think I have found the culprit:

https://github.com/carson-katri/dream-textures/blame/f70c30dc7fadf4677f9401e9a33ef00e47f47e54/property_groups/dream_prompt.py#L240

**Comment by GottfriedHofmann** [comment]
Changing it to

`        with open(self.filepath, 'w', encoding='utf-8') as target:
            args = selection.generate_args()
            args['seed'] = selection.seed
            args['scheduler'] = selection.scheduler
            args['step_preview_mode'] = selection.step_preview_mode
            del args['optimizations'] # optimization args are in already
            del args['outpaint_origin'] # this essentially removes outpainting from being stored in the JSON, should come back
            json.dump(args, target, indent=4)`

allows to export a valid JSON, but loading it again fails:

> view_history.py", line 154, in execute
    setattr(context.scene.dream_textures_prompt, key, value)
TypeError: bpy_struct: item.attr = val: expected a string enum, not int
