### ISSUE TITLE
All models dissapeared and can't be installed again

### ISSUE THREAD

**Issue by Mtjslk** [carson-katri/dream-textures#537]
### Description

I have sucessfully downloaded and used the stabilityai/stable-diffusion-2-1 and stabilityai/stable-diffusion-2-depth models. But then I tried downloading some inpainting model, after that all previously installed models disappeared and now I can't download any of them. When I click on download button it shows some progress, but than nothing happens. I've tried to reinstall the addon, and use it in different blender versions, but no luck.

### Steps to Reproduce

1. open preferences
2. press download on some model
3. nothing happens

### Expected Behavior

clicking on download button should allow the model to be installed

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Please check Window > Toggle System Console for an error message.

**Comment by Mtjslk** [comment]
This is everything I get from starting blender, installing the addon to trying download the default stable diffusion model


Read prefs: C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
addon_utils.disable: dream_textures not disabled
Modules Installed (dream_textures) from 'D:\\Addons\\dream_textures-windows-cuda.zip' into 'C:\\Users\\matej\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'
Exception: Traceback (most recent call last):
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 271, in _receive
    response = getattr(self, message.method_name)(*message.args, **message.kwargs)
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 90, in hf_list_installed_models
    return [_map_model(file) for file in os.listdir(DIFFUSERS_CACHE) if os.path.isdir(os.path.join(DIFFUSERS_CACHE, file))]
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 90, in <listcomp>
    return [_map_model(file) for file in os.listdir(DIFFUSERS_CACHE) if os.path.isdir(os.path.join(DIFFUSERS_CACHE, file))]
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 72, in _map_model
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\matej/.cache\\huggingface\\diffusers\\models--stabilityai--stable-diffusion-x4-upscaler\\refs\\main'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 111, in run_callbacks
    done_callback(self)
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\preferences.py", line 185, in on_done
    set_model_list('installed_models', future.result())
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 58, in result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\matej/.cache\\huggingface\\diffusers\\models--stabilityai--stable-diffusion-x4-upscaler\\refs\\main'
C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\configuration_utils.py:229: FutureWarning:  The function get_config_dict is deprecated. Please use <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>.load_config instead. This function will be removed in version v1.0.0
  deprecate("get_config_dict", "1.0.0", deprecation_message, standard_warn=False)
Fetching 16 files: 16it [00:00, 2283.70it/s]
Exception: Traceback (most recent call last):
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 271, in _receive
    response = getattr(self, message.method_name)(*message.args, **message.kwargs)
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 90, in hf_list_installed_models
    return [_map_model(file) for file in os.listdir(DIFFUSERS_CACHE) if os.path.isdir(os.path.join(DIFFUSERS_CACHE, file))]
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 90, in <listcomp>
    return [_map_model(file) for file in os.listdir(DIFFUSERS_CACHE) if os.path.isdir(os.path.join(DIFFUSERS_CACHE, file))]
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 72, in _map_model
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\matej/.cache\\huggingface\\diffusers\\models--stabilityai--stable-diffusion-x4-upscaler\\refs\\main'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 111, in run_callbacks
    done_callback(self)
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\preferences.py", line 145, in on_done
    set_model_list('installed_models', Generator.shared().hf_list_installed_models().result())
  File "C:\Users\matej\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 64, in result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\matej/.cache\\huggingface\\diffusers\\models--stabilityai--stable-diffusion-x4-upscaler\\refs\\main'

**Comment by Mtjslk** [comment]
Can someone help out with this?

**Comment by carson-katri** [comment]
Please update to v0.1.0, this bug was fixed.
