### ISSUE TITLE
AI Upscale stuck with error in console

### ISSUE THREAD

**Issue by vlarin** [carson-katri/dream-textures#546]
### Description

Hi! Addon works fine with image generation and depth mode, however when I try to AI upscale I stuck with the following error in the blender console:

Fetching 14 files: 100%|█████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 4316.08it/s]
Exception: Traceback (most recent call last):
  File "C:\Users\larin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 273, in _receive
    for res in iter(response):
  File "C:\Users\larin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\upscale.py", line 52, in upscale
    low_res_image = Image.fromarray(image)
  File "C:\Users\larin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\PIL\Image.py", line 2982, in fromarray
    arr = obj.__array_interface__
AttributeError: 'str' object has no attribute '__array_interface__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\larin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 111, in run_callbacks
    done_callback(self)
  File "C:\Users\larin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\upscale.py", line 114, in image_done
    tile: ImageUpscaleResult = future.result()
  File "C:\Users\larin\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 58, in result
    raise self._exception
AttributeError: 'str' object has no attribute '__array_interface__'

### Steps to Reproduce

1. Set any parameters in AI upscale tab
2. Press "AI upscale"
3. System stuck in "Starting state with error log indefinitely"
![image](https://user-images.githubusercontent.com/1154269/216390153-e042aa40-f7de-4362-b2cc-b9696e902500.png)

### Expected Behavior

The action should do AI upscaling

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Upscaling was fixed in #410. That will be included in the next release.
