### ISSUE TITLE
"Generate"-button give error message, no picture.

### ISSUE THREAD

**Issue by Ubuntuuuuu** [carson-katri/dream-textures#548]
### Description

Dream Texture version: 0.0.9
Blender version: 3.4.1
GPU: RTX 2070
OS: Windows 10

Installed ok, 
![image](https://user-images.githubusercontent.com/115940115/216577119-f8ff0bcc-3630-4b52-9129-ec1f09c1242d.png)
 But "Generate" not give any image.
 
 This error message in system console:
 
 ```
Modules Installed (dream_textures) from 'C:\\Users\\user\\Downloads\\BLENDER_FREE_ADDONS\\dream_textures-windows-cuda.zip' into 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'
Exception: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 273, in _receive
    for res in iter(response):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 411, in prompt_to_image
    pipe = GeneratorPipeline.from_pretrained(
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\pipeline_utils.py", line 711, in from_pretrained
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\transformers\tokenization_utils_base.py", line 1785, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'C:\Users\user/.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-1\snapshots\36a01dc742066de2e8c91e7cf0b8f6b53ef53da1'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'C:\Users\user/.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-1\snapshots\36a01dc742066de2e8c91e7cf0b8f6b53ef53da1' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 98, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 139, in exception_callback
    raise exception
OSError: Can't load tokenizer for 'C:\Users\user/.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-1\snapshots\36a01dc742066de2e8c91e7cf0b8f6b53ef53da1'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'C:\Users\user/.cache\huggingface\diffusers\models--stabilityai--stable-diffusion-2-1\snapshots\36a01dc742066de2e8c91e7cf0b8f6b53ef53da1' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
```
`

Any clue what is wrong? Is there any needs more to install?

### Steps to Reproduce

1. Go to Dream Texture
2. Giving subject, like "bird"
3. pressing "Generate"

### Expected Behavior

I expected that it would work like earlier. Make a picture asked...

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Try deleting the model and redownloading it. The model folder can be found by clicking the folder icon next to the model in the list.

**Comment by enzyme69** [comment]
I got similar issue maybe related error. I can't get anything out of 2.1 model. There might be a bug related to this:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6923

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/dream_textures/generator_process/actor.py", line 98, in run_callbacks
    exception_callback(self, exception)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/dream_textures/operators/dream_texture.py", line 139, in exception_callback
    raise exception
OSError: Error no file named diffusion_pytorch_model.bin found in directory /Users/jimmygunawan/.cache/huggingface/diffusers/models--stabilityai--stable-diffusion-2-1/snapshots/36a01dc742066de2e8c91e7cf0b8f6b53ef53da1.
/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/dream_textures/.python_dependencies/diffusers/configuration_utils.py:229: FutureWarning:  The function get_config_dict is deprecated. Please use <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>.load_config instead. This function will be removed in version v1.0.0
  deprecate("get_config_dict", "1.0.0", deprecation_message, standard_warn=False)
```

Using different ckpt like Anything, it actually works and produces result.

**Comment by Ubuntuuuuu** [comment]
Tried, no help:

`The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 98, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\dream_texture.py", line 139, in exception_callback
    raise exception
OSError: Error no file named model_index.json found in directory C:\Users\user/.cache\huggingface\diffusers\models--andite--anything-v4.0\snapshots\8eb1055fba5a23bf1b60d52cdc620f84b25ca054.`
