### ISSUE TITLE
Everything is set. But doesn't work. Creates a black texture.

### ISSUE THREAD

**Issue by neon1978** [carson-katri/dream-textures#554]
### Description

The error gives out even when I spend the cursor on the tab. I don't press anything.

### Steps to Reproduce

Traceback (most recent call last):
  File "C:\Users\Admin™\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\project.py", line 61, in draw
    models = list(filter(
  File "C:\Users\Admin™\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\operators\project.py", line 62, in <lambda>
    lambda m: m.model == context.scene.dream_textures_project_prompt.model,
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte

### Expected Behavior

Processor	AMD Ryzen 9 5950X 
RAM	64,0 GB
NVIDIA GeForge RTX 3070 Ti
Python 3.10
Blender 3.4.1

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by neon1978** [comment]
This problem was with version 0.0.9.
Version 0.1.0 worked without problems.
