### ISSUE TITLE
Unable to download any models from the addon

### ISSUE THREAD

**Issue by Jh12rss** [carson-katri/dream-textures#562]
### Description

Issue is present on both the beta version and the production version, unable to download stable diffusion models, a small flickering happens when trying to download the model and the logs says the following:

Read prefs: C:\Users\Ussha\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Exception: Traceback (most recent call last):
  File "C:\Users\Ussha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 271, in _receive
    response = getattr(self, message.method_name)(*message.args, **message.kwargs)
  File "C:\Users\Ussha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 84, in hf_list_installed_models
    from diffusers.utils import DIFFUSERS_CACHE
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\configuration_utils.py", line 35, in <module>
    from .utils import DIFFUSERS_CACHE, HUGGINGFACE_CO_RESOLVE_ENDPOINT, DummyObject, deprecate, logging
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\utils\__init__.py", line 68, in <module>
    from .torch_utils import randn_tensor
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\utils\torch_utils.py", line 24, in <module>    import torch
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\__init__.py", line 881, in <module>
    from torch import onnx as onnx
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\__init__.py", line 12, in <module>
    from . import (  # usort:skip. Keep the order instead of sorting lexicographically
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\errors.py", line 9, in <module>
    from torch.onnx._internal import diagnostics
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\__init__.py", line 1, in <module>
    from ._diagnostic import (
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\_diagnostic.py", line 7, in <module>
    from torch.onnx._internal.diagnostics import _rules, infra
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\_rules.py", line 12, in <module>
    from torch.onnx._internal.diagnostics import infra
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\__init__.py", line 1, in <module>
    from ._infra import (
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\_infra.py", line 9, in <module>
    from torch.onnx._internal.diagnostics.infra import formatter, sarif
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\formatter.py", line 6, in <module>
    from torch.onnx._internal.diagnostics.infra import sarif
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\sarif\__init__.py", line 18, in <module>
    from torch.onnx._internal.diagnostics.infra.sarif._conversion import Conversion
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\sarif\_conversion.py", line 9, in <module>
    from torch.onnx._internal.diagnostics.infra.sarif import (
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\sarif\_tool.py", line 9, in <module>
    from torch.onnx._internal.diagnostics.infra.sarif import _property_bag, _tool_component
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\sarif\_tool_component.py", line 11, in <module>
    from torch.onnx._internal.diagnostics.infra.sarif import (
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\sarif\_reporting_descriptor.py", line 9, in <module>
    from torch.onnx._internal.diagnostics.infra.sarif import (
ImportError: cannot import name '_reporting_descriptor_relationship' from partially initialized module 'torch.onnx._internal.diagnostics.infra.sarif' (most likely due to a circular import) (C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\sarif\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ussha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 111, in run_callbacks
    done_callback(self)
  File "C:\Users\Ussha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\preferences.py", line 190, in on_done
    set_model_list('installed_models', future.result())
  File "C:\Users\Ussha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 58, in result
    raise self._exception
ImportError: cannot import name '_reporting_descriptor_relationship' from partially initialized module 'torch.onnx._internal.diagnostics.infra.sarif' (most likely due to a circular import) (C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\onnx\_internal\diagnostics\infra\sarif\__init__.py)
Exception: Traceback (most recent call last):
  File "C:\Users\Ussha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actor.py", line 271, in _receive
    response = getattr(self, message.method_name)(*message.args, **message.kwargs)
  File "C:\Users\Ussha\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 84, in hf_list_installed_models
    from diffusers.utils import DIFFUSERS_CACHE
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\configuration_utils.py", line 35, in <module>
    from .utils import DIFFUSERS_CACHE, HUGGINGFACE_CO_RESOLVE_ENDPOINT, DummyObject, deprecate, logging
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\utils\__init__.py", line 68, in <module>
    from .torch_utils import randn_tensor
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\diffusers\utils\torch_utils.py", line 24, in <module>
    import torch
  File "C:\Users\Ussha\AppData\Local\Packages\BlenderFoundation.Blender_ppwjx1n5r4v9t\LocalCache\Roaming\Blender Foundation\Blender\3.4\scripts\addons\dream_textures\.python_dependencies\torch\__init__.py", line 249, in <module>
    for name in dir(_C):
NameError: name '_C' is not defined

### Steps to Reproduce

1) Install the version found on the release page
2) Unzip the file, and install the zipped file as an addon
3) Try to download any stable diffusion model
4) error

### Expected Behavior

Model should be loaded

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by BUGProtectionAssociation** [comment]
#454 #549 
This is a common problem. But the developers seem to be doing something else

**Comment by carson-katri** [comment]
This issue was discussed in Discord, and it is related to using a Windows Store version of Blender. Using the installer on blender.org should work.
