### ISSUE TITLE
can't install on linux,

### ISSUE THREAD

**Issue by ArlanCooper** [carson-katri/dream-textures#606]
### Description

i try this command:
pip install basicsr

and got this error:
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting basicsr
  Using cached http://mirrors.cloud.aliyuncs.com/pypi/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
      ERROR: Could not find a version that satisfies the requirement cython (from versions: none)
      ERROR: No matching distribution found for cython
      /root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/setuptools/dist.py:773: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
        % (opt, underscore_opt)
      /root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        SetuptoolsDeprecationWarning,
      Traceback (most recent call last):
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/root/miniconda3/envs/stabledifussion/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1vuz1b_c', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'cython']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vv8ukm9p/basicsr_ea54f18f830c4a62be30b0a4c8254497/setup.py", line 172, in <module>
          **setup_kwargs)
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/setuptools/dist.py", line 877, in fetch_build_eggs
          replace_conflicting=True,
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
          replace_conflicting=replace_conflicting
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/root/miniconda3/envs/stabledifussion/lib/python3.7/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/root/miniconda3/envs/stabledifussion/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp1vuz1b_c', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'cython']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Steps to Reproduce

just can't install 

### Expected Behavior

how to fix it 

### Addon Version

Other (Built from source)

### GPU

NVIDIA

**Comment by NullSenseStudio** [comment]
Why are you trying to install basicsr? I don't believe this package is used in recent versions of Dream Textures.

**Comment by ArlanCooper** [comment]
I installed successed after tried many times
