### ISSUE TITLE
TypeError('expected str, bytes or os.PathLike object, not NoneType')

### ISSUE THREAD

**Issue by teejay5** [carson-katri/dream-textures#685]
### Description

I got the error TypeError('expected str, bytes or os.PathLike object, not NoneType') after installing and trying to generate a prompt using Stable Diffusion 2.1. The plugin works with Stable Diffusion 1.4 though. 

Blender 3.5.1

Specs:
AMD Ryzen 7 8-Core Processor
NVIDIA GeForce RTX 2070 SUPER
16GB DDR4

### Steps to Reproduce

Install dream_textures-windows-cuda
Download StableDiffusion 2.1
Enter a prompt
Try to generate an image

### Expected Behavior

The prompt should generate an image without throwing an error

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by ais-lingua** [comment]
I just installed for the first time on Intel i5 12,  blender 3.51 and got the same error.

**Comment by a-whall** [comment]
Same issue and hardware as teejay. Blender 3.5.
I couldn't get any model to work, all were downloaded via the preferences model-search feature.
For the following error, I was using `stabilityai/stable-diffusion-2-1-base` as the [setup](https://github.com/carson-katri/dream-textures/wiki/Setup#download-a-model) suggests.

```
Exception: Traceback (most recent call last):
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actor.py", line 157, in _receive
    for res in iter(response):
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 594, in prompt_to_image
    pipe = load_pipe(self, "prompt", GeneratorPipeline, model, optimizations, scheduler, device)
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 64, in load_pipe
    pipe = generator_pipeline.from_pretrained(
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\.python_dependencies\diffusers\pipelines\pipeline_utils.py", line 1021, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\.python_dependencies\diffusers\pipelines\pipeline_utils.py", line 445, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\.python_dependencies\transformers\tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\.python_dependencies\transformers\tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\.python_dependencies\transformers\models\clip\tokenization_clip.py", line 324, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\generator_process\future.py", line 87, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\___\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\dream_textures\operators\dream_texture.py", line 166, in exception_callback
    raise exception
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

vocab_file is None.

**Comment by aminmarandi** [comment]
I have the same issue and there's no solution.

**Comment by DefNotYashar** [comment]
same here

**Comment by JacRossiter** [comment]
Same, did anyone find a solution?

**Comment by DefNotYashar** [comment]
not yet, what version of blender are you using?

**Comment by JacRossiter** [comment]
3.5.1

**Comment by carson-katri** [comment]
Try deleting the model (click the folder icon and delete its folder) and reinstalling. It’s possible some files just failed to download.

**Comment by aminmarandi** [comment]
Hi Carson, I did delete the model so many times and reinstalled. Even uninstalled and reinstalled blender with different versions from 3.3 to the most current but its still giving the same error

**Comment by carson-katri** [comment]
@aminmarandi Please send the output of Window > Toggle System Console so I can verify the issue is the same.

**Comment by aminmarandi** [comment]
@carson-katri here is the message from the toggle console: 

Read prefs: C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
Info: Deleted 3 object(s)

Fetching 15 files:   0%|                                                                        | 0/15 [00:00<?, ?it/s]
Downloading (…)1c7/unet/config.json: 100%|█████████████████████████████████████████████| 980/980 [00:00<00:00, 178kB/s]
Downloading (…)71c7/vae/config.json: 100%|████████████████████████████████████████████| 621/621 [00:00<00:00, 97.6kB/s]
Downloading (…)on_pytorch_model.bin: 100%|██████████████████████████████████████████| 167M/167M [00:02<00:00, 57.8MB/s]
Downloading (…)on_pytorch_model.bin: 100%|████████████████████████████████████████| 1.73G/1.73G [00:17<00:00, 97.0MB/s]
Exception: Traceback (most recent call last):▋                                     | 157M/1.73G [00:02<00:26, 59.1MB/s]
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\actor.py", line 157, in _receive
    for res in iter(response):
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\actions\huggingface_hub.py", line 203, in hf_snapshot_download
    _snapshot_download.snapshot_download(
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\huggingface_hub\_snapshot_download.py", line 235, in snapshot_download
    thread_map(
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\huggingface_hub\_snapshot_download.py", line 212, in _inner_hf_hub_download
    return hf_hub_download(
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\huggingface_hub\file_download.py", line 1302, in hf_hub_download
    with FileLock(lock_path):
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\filelock\_api.py", line 260, in __enter__
    self.acquire()
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\filelock\_api.py", line 217, in acquire
    self._acquire()
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\filelock\_windows.py", line 25, in _acquire
    fd = os.open(self.lock_file, flags, self._context.mode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\aminm\\.cache\\huggingface\\hub\\models--stabilityai--stable-diffusion-2-depth\\blobs\\W/"9b4ddcd469a0a6b0c68db771a535a43ac1255158.lock'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\future.py", line 87, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\preferences.py", line 141, in on_exception
    raise exception
OSError: [Errno 22] Invalid argument: 'C:\\Users\\aminm\\.cache\\huggingface\\hub\\models--stabilityai--stable-diffusion-2-depth\\blobs\\W/"9b4ddcd469a0a6b0c68db771a535a43ac1255158.lock'
Exception: Traceback (most recent call last):
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\actor.py", line 157, in _receive
    for res in iter(response):
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\actions\depth_to_image.py", line 334, in depth_to_image
    pipe = load_pipe(self, "depth", GeneratorPipeline, model, optimizations, scheduler, device)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\actions\prompt_to_image.py", line 64, in load_pipe
    pipe = generator_pipeline.from_pretrained(
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\diffusers\pipelines\pipeline_utils.py", line 1021, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\diffusers\pipelines\pipeline_utils.py", line 445, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\transformers\tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\transformers\tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\.python_dependencies\transformers\models\clip\tokenization_clip.py", line 322, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\generator_process\future.py", line 87, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\aminm\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\dream_textures\operators\project.py", line 418, in on_exception
    raise exception
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by pixelrogueart** [comment]
any solution?

**Comment by 2442-pixeles** [comment]
same problem

**Comment by Hunanbean** [comment]
Same exact issue

**Comment by aminmarandi** [comment]
> any solution?

I tried everything and nothing works so just waiting on @carson-katri to check the Window > Toggle System Console I shared and see if we can resolve it. Seems like so many have the same issue

**Comment by pixelrogueart** [comment]
> > any solution?
> 
> I tried everything and nothing works so just waiting on @carson-katri to check the Window > Toggle System Console I shared and see if we can resolve it. Seems like so many have the same issue

Yeah me too, what's your GPU? I'm starting to think it's a bug related to rtx 3060.

**Comment by Hunanbean** [comment]
For me the issue resolved itself, seemingly after i downloaded some
ControlNets. I was rapidly trying many things to attempt to fix it, so i
cannot be sure that, that is what did it

**Comment by aminmarandi** [comment]
hey guys it finally worked for me! @Hunanbean downloaded the ControlNet models and also updated my NVIDIA Driver, also not sure if it matters but I installed blender 3.4 which I heard works the best! thanks guys for the help!

**Comment by aminmarandi** [comment]
@pixelrogueart my GPU is 2070 RTX I have updated the driver and installed a few ControlNet models and now its working! try it!

**Comment by pixelrogueart** [comment]
> @pixelrogueart my GPU is 2070 RTX I have updated the driver and installed a few ControlNet models and now its working! try it!

Thank you! Will try it asap and let you guyts know if it works!
