### ISSUE TITLE
error installing dependencies on windows

### ISSUE THREAD

**Issue by NickKauf** [carson-katri/dream-textures#7]
windows 10. Blender 3.2.1 ran as administrator from windows explorer with right-click.
`
Collecting k-diffusion
  Cloning https://github.com/lstein/k-diffusion.git (to revision master) to c:\users\nkauf\appdata\local\temp\pip-install-xbdqugbe\k-diffusion_32dd955250f04eecbefc0143af56f330
  Running command git clone -q https://github.com/lstein/k-diffusion.git 'C:\Users\nkauf\AppData\Local\Temp\pip-install-xbdqugbe\k-diffusion_32dd955250f04eecbefc0143af56f330'
  Resolved https://github.com/lstein/k-diffusion.git to commit ef1bf07627c9a10ba9137e68a0206b844544a7d9
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Obtaining file:///C:/Users/nkauf/AppData/Roaming/Blender%20Foundation/Blender/3.2/scripts/addons/dream_textures/stable_diffusion (from -r C:\Users\nkauf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\requirements-win32.txt (line 32))
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\bin\python.EXE' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nkauf\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons\\dream_textures\\stable_diffusion\\setup.py'"'"'; __file__='"'"'C:\\Users\\nkauf\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons\\dream_textures\\stable_diffusion\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\nkauf\AppData\Local\Temp\pip-pip-egg-info-nflaht66'
         cwd: C:\Users\nkauf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\
    Complete output (28 lines):
    Traceback (most recent call last):
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\pkg_resources\__init__.py", line 2851, in get_entry_map
        ep_map = self._ep_map
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\pkg_resources\__init__.py", line 2813, in __getattr__
        raise AttributeError(attr)
    AttributeError: _ep_map. Did you mean: '_dep_map'?

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\nkauf\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\dream_textures\stable_diffusion\setup.py", line 3, in <module>
        setup(
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\setuptools\__init__.py", line 142, in _install_setup_requires
        dist = MinimalDistribution(attrs)
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\setuptools\__init__.py", line 134, in __init__
        distutils.core.Distribution.__init__(self, filtered)
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\setuptools\dist.py", line 451, in __init__
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\pkg_resources\__init__.py", line 641, in <genexpr>
        for entry in dist.get_entry_map(group).values()
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\pkg_resources\__init__.py", line 2853, in get_entry_map
        ep_map = self._ep_map = EntryPoint.parse_map(
      File "C:\Users\nkauf\Blender Foundation\stable\blender-3.2.1+stable.a2d59b2dac9e\3.2\python\lib\site-packages\pkg_resources\__init__.py", line 2538, in parse_map
        raise ValueError("Entry points must be listed in groups")
    ValueError: Entry points must be listed in groups`

**Comment by 3DManuH** [comment]
i am getting an error as well when installing dependecies.
![h3hmtaHu9H](https://user-images.githubusercontent.com/63927992/189865896-8001a37d-23b1-416f-8abe-3d6e7b29aad8.jpg)

**Comment by carson-katri** [comment]
@3DManuH Please go to Window > Toggle System Console to see what the actual error message is.

**Comment by carson-katri** [comment]
@NickKauf Can you try repeating the process with a fresh install of Blender 3.3?

**Comment by 3DManuH** [comment]
already tried. same issue

Carson Katri ***@***.***> schrieb am Di. 13. Sept. 2022 um
13:52:

**Comment by carson-katri** [comment]
What do your logs say. Is it the same as OPs error report, or is it something else?

**Comment by RedLogicP** [comment]
I'm getting the exact same issue on Windows 10 with a fresh 3.3 install

**Comment by SandrewArt** [comment]
![image](https://user-images.githubusercontent.com/113932906/191076196-422f3878-9411-478f-922e-eb853d237930.png)

i have this error now, i tried to run the command but it says invalid syntax

**Comment by carson-katri** [comment]
@SandrewArt  this is a different error. You just need to download the file `dream_textures.zip` from releases. It looks like you downloaded the source code instead.

**Comment by SurrealWhispers** [comment]
I'm having the same issue as @SandrewArt 
I'm using the file from releases but it doesn't work still.

**Comment by SurrealWhispers** [comment]
> @SurrealWhispers If the file is called `dream-textures-main.zip`, it’s the wrong one. Can you show your exact error message (preferably in a new issue or a discussion post?)

The file is called dream_textures.zip. I'll make a new post.

**Comment by carson-katri** [comment]
Please take a look at [v0.0.6](https://github.com/carson-katri/dream-textures/releases/tag/0.0.6), which removes the need to install dependencies.
