### ISSUE TITLE
Python: Traceback in exists : path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by ajarcon** [carson-katri/dream-textures#744]
### Description

P
![Screenshot 2023-11-15 194514](https://github.com/carson-katri/dream-textures/assets/98292515/da829e45-ef92-49fe-9736-d551776eed98)
ython: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### Steps to Reproduce

Install blender 4.0 and install dream textures

### Expected Behavior

It loads and installs properly

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by ajarcon** [comment]
very likely to be an incompatible bug with Blender 4.0 as I got a different error when I restarted it


Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\liuli\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\__init__.py", line 39, in <module>
    from .render_pass import register_render_pass, unregister_render_pass, pass_inputs
  File "C:\Users\liuli\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\render_pass.py", line 7, in <module>
    from .generator_process import Generator
  File "C:\Users\liuli\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\__init__.py", line 3, in <module>
    class Generator(Actor):
  File "C:\Users\liuli\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\__init__.py", line 9, in Generator
    from .actions.load_model import load_model
  File "C:\Users\liuli\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\actions\load_model.py", line 4, in <module>
    from ..models import Checkpoint, ModelConfig, Scheduler
  File "C:\Users\liuli\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\models\__init__.py", line 2, in <module>
    from .image_generation_result import *
  File "C:\Users\liuli\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\models\image_generation_result.py", line 6, in <module>
    from ...api.models.step_preview_mode import StepPreviewMode
ModuleNotFoundError: No module named 'dream_textures.api'

**Comment by WalidAliAlfaid** [comment]
Same issue, did you find a solution?

**Comment by ajarcon** [comment]
Nopr
