### ISSUE TITLE
ModuleNotFoundError: No module named 'dream_textures.api' error

### ISSUE THREAD

**Issue by yengalvez** [carson-katri/dream-textures#748]
### Description

I'm having this error with Blender 3.6.1

I can't enable the plugin.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dream_textures\__init__.py", line 39, in <module>
    from .render_pass import register_render_pass, unregister_render_pass, pass_inputs
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dream_textures\render_pass.py", line 7, in <module>
    from .generator_process import Generator
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dream_textures\generator_process\__init__.py", line 3, in <module>
    class Generator(Actor):
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dream_textures\generator_process\__init__.py", line 9, in Generator
    from .actions.load_model import load_model
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dream_textures\generator_process\actions\load_model.py", line 4, in <module>
    from ..models import Checkpoint, ModelConfig, Scheduler
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dream_textures\generator_process\models\__init__.py", line 2, in <module>
    from .image_generation_result import *
  File "C:\Users\info\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\dream_textures\generator_process\models\image_generation_result.py", line 6, in <module>
    from ...api.models.step_preview_mode import StepPreviewMode
ModuleNotFoundError: No module named 'dream_textures.api'

### Steps to Reproduce

1. Install plug-in
2. Try to enable

### Expected Behavior

Enable it

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by yengalvez** [comment]
Ok, I was able to run it extracting the zip and overwriting all directly over the script directory

**Comment by wizard3376** [comment]
Can you clarify where this script directory is located?
