### ISSUE TITLE
no module named dream_textures.api

### ISSUE THREAD

**Issue by nohansantosfrancos** [carson-katri/dream-textures#753]
### Description

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\__init__.py", line 39, in <module>
    from .render_pass import register_render_pass, unregister_render_pass, pass_inputs
  File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\render_pass.py", line 7, in <module>
    from .generator_process import Generator
  File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\__init__.py", line 3, in <module>
    class Generator(Actor):
  File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\__init__.py", line 9, in Generator
    from .actions.load_model import load_model
  File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\actions\load_model.py", line 4, in <module>
    from ..models import Checkpoint, ModelConfig, Scheduler
  File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\models\__init__.py", line 2, in <module>
    from .image_generation_result import *
  File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\models\image_generation_result.py", line 6, in <module>
    from ...api.models.step_preview_mode import StepPreviewMode
ModuleNotFoundError: No module named 'dream_textures.api'

### Steps to Reproduce

i click on install and it give this error

### Expected Behavior

it give an error

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by wizard3376** [comment]
How to fix it ?

**Comment by wizard3376** [comment]
To solve this you just need to go here C:\Users\Username here\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\
and manually unzip this addon here so that it is there as a folder, that’s all, if you have any questions, ask!

**Comment by Fhalo48** [comment]
Hi

I'm getting the same error with blender V3.3, the addon already expanded. Any suggestions

**Comment by Fhalo48** [comment]
uPDATE:

Removed old copy of the dream_texture folder
Then manual unzip it solved my problem

**Comment by 1mjc** [comment]
> To solve this you just need to go here C:\Users\Username here\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons and manually unzip this addon here so that it is there as a folder, that’s all, if you have any questions, ask!

W

**Comment by Brandon20-Flex** [comment]
how do you do manual unzipping
