### ISSUE TITLE
there is no module named dream_textures.api

### ISSUE THREAD

**Issue by wizard3376** [carson-katri/dream-textures#755]
Description
Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
mod = importlib.import_module(module_name)
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1050, in _gcd_import
File "", line 1027, in find_and_load
File "", line 1006, in find_and_load_unlocked
File "", line 688, in load_unlocked
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures_init.py", line 39, in
from .render_pass import register_render_pass, unregister_render_pass, pass_inputs
File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\render_pass.py", line 7, in
from .generator_process import Generator
File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process_init.py", line 3, in
class Generator(Actor):
File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process_init.py", line 9, in Generator
from .actions.load_model import load_model
File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\actions\load_model.py", line 4, in
from ..models import Checkpoint, ModelConfig, Scheduler
File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\models_init.py", line 2, in
from .image_generation_result import *
File "C:\Users\nohan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dream_textures\generator_process\models\image_generation_result.py", line 6, in
from ...api.models.step_preview_mode import StepPreviewMode
ModuleNotFoundError: No module named 'dream_textures.api'

Steps to Reproduce
i click on install and it give this error

Expected Behavior
it give an error

Addon Version
Windows (CUDA)

GPU
NVIDIA
Help is needed!!!

**Comment by ggxxii** [comment]
hi,  I also encountered this problem, u just need to manually unzip the file into the blender add-on path in your C:/

**Comment by wizard3376** [comment]
Thank you!! but now the next problem: stable diffusion 2.1 is not installed, what should I do?
