### ISSUE TITLE
 matches no enum in 'DreamPrompt', '', 'backend'

### ISSUE THREAD

**Issue by strawberryPunch** [carson-katri/dream-textures#770]
### Description

WARN (bpy.rna): C:\Users\blender\git\blender-v360\blender.git\source\blender\python\intern\bpy_rna.c:1343 pyrna_enum_to_py: current value '1' matches no enum in 'DreamPrompt', '', 'backend'

please help me!

### Steps to Reproduce

1

### Expected Behavior

1

### Addon Version

Windows (CUDA)

### GPU

NVIDIA

**Comment by alexmro** [comment]
I have the same thing in Blender 4.0.3. It is so hard to tedious to make this thing work. It tells me that no model has been selected even though I do have it downloaded and selected. And this is the only warning I see in the console

**Comment by Gerkinfeltser** [comment]
I'm seeing the same behavior. I'm also seeing the following when starting Blender from the command line (the error does not occur if the DreamPrompt addon is not enabled).

I'm on Windows 10 running Blender 4.0.2.

```
(base) PS C:\Program Files\Blender Foundation\Blender 4.0> .\blender.exe
Read prefs: "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\multiprocessing\spawn.py", line 125, in _main    
    prepare(preparation_data)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\multiprocessing\spawn.py", line 236, in prepare  
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\runpy.py", line 252, in _get_code_from_file      
    with io.open_code(decoded_path) as f:
OSError: [Errno 22] Invalid argument: 'C:\\Program Files\\Blender Foundation\\Blender 4.0\\<blender string>'
```
