### ISSUE TITLE
<title> Blender 4.1 install issue compatibility with Dream Texture (AMD Version)

### ISSUE THREAD

**Issue by gioxyer** [carson-katri/dream-textures#786]
### Description

Python: Traceback (most recent call last):
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

![image](https://github.com/carson-katri/dream-textures/assets/161426313/bf636e03-385d-4ec1-a0c8-d8aa2bf162fb)

Console log:

File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\startup\bl_operators\userpref.py", line 697, in execute
    file_to_extract.extractall(path_addons)
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\zipfile.py", line 1735, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\giorg\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\addons\\dream_textures\\.python_dependencies\\transformers\\models\\deprecated\\trajectory_transformer\\__pycache__\\convert_trajectory_transformer_original_pytorch_checkpoint_to_pytorch.cpython-310.pyc'
Add-on not loaded: "dream_textures", cause:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\startup\bl_operators\userpref.py", line 450, in execute
    mod = addon_utils.enable(self.module, default_set=True, handle_error=err_cb)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 329, in enable
    if mod and os.path.exists(mod.__file__):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Error: Python: Traceback (most recent call last):
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### Steps to Reproduce

Download from website AMD Version
Install from AddOn 
Enable AddOn (error display, can't enable it)

### Expected Behavior

AddOn should enable when check the box, but display an error :

Python: Traceback (most recent call last):
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### Addon Version

Other (Built from source)

### GPU

AMD (unsupported for local generation)

**Comment by gioxyer** [comment]
Fixed with CUDA windows version with clean install from %appdata%
