### ISSUE TITLE
No module named 'dream_textures.api'

### ISSUE THREAD

**Issue by ZenRepublic** [carson-katri/dream-textures#790]
### Description

can't enable the plugin :<

### Steps to Reproduce

1. download the plugin and add it into blender 3.6
2. try to enable it

### Expected Behavior

should work lmao

### Addon Version

Windows (CUDA)

### GPU

AMD (unsupported for local generation)

**Comment by ZenRepublic** [comment]
![image](https://github.com/carson-katri/dream-textures/assets/102485601/028625fe-78a7-4282-8c6f-c6b64a666f27)

**Comment by Darfiss** [comment]
Description

can't enable the plugin :<
Steps to Reproduce
 download the plugin and add it into blender 4.1 (couldnt find out which blenderversion is supported.. will retry with 3.6)
 try to enable it

Expected Behavior
should work lmao

Addon Version
Windows (CUDA)

GPU
RTX 3050 Mobile


InfoLog:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Steffen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\dream_textures\__init__.py", line 39, in <module>
    from .render_pass import register_render_pass, unregister_render_pass, pass_inputs
  File "C:\Users\Steffen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\dream_textures\render_pass.py", line 7, in <module>
    from .generator_process import Generator
  File "C:\Users\Steffen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\dream_textures\generator_process\__init__.py", line 3, in <module>
    class Generator(Actor):
  File "C:\Users\Steffen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\dream_textures\generator_process\__init__.py", line 9, in Generator
    from .actions.load_model import load_model
  File "C:\Users\Steffen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\dream_textures\generator_process\actions\load_model.py", line 4, in <module>
    from ..models import Checkpoint, ModelConfig, Scheduler
  File "C:\Users\Steffen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\dream_textures\generator_process\models\__init__.py", line 2, in <module>
    from .image_generation_result import *
  File "C:\Users\Steffen\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\dream_textures\generator_process\models\image_generation_result.py", line 6, in <module>
    from ...api.models.step_preview_mode import StepPreviewMode
ModuleNotFoundError: No module named 'dream_textures.api'
