### ISSUE TITLE
Unable to download Stable Diffusion. Issue with fbgemm.dll module.

### ISSUE THREAD

**Issue by vladyslav-zaichyk** [carson-katri/dream-textures#817]
### Description

Blender version 4.2.1 LTS

After installing the latest `dream_textures-windows-cuda-4-1.7z` release, the downloading of Stable Diffusion is stuck on 0%.
I tried to reinstall the plugin and reinstalling blender itself. The problem persists.

![image](https://github.com/user-attachments/assets/7a925118-2689-4730-9f52-b7d175e5bffe)

System console output after installing plugin:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Valdemar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\__init__.py", line 3, in <module>
    from .actor import Actor, is_actor_process
  File "C:\Users\Valdemar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\actor.py", line 51, in <module>
    _load_dependencies()
  File "C:\Users\Valdemar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\actor.py", line 46, in _load_dependencies
    _patch_zip_direct_transformers_import()
  File "C:\Users\Valdemar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\actor.py", line 21, in _patch_zip_direct_transformers_import
    from transformers.utils import import_utils
  File "C:\Users\runneradmin\AppData\Local\Temp\pip-target-k9ekwdk7\lib\python\transformers/__init__.py", line 26, in <module>
  File "C:\Users\runneradmin\AppData\Local\Temp\pip-target-k9ekwdk7\lib\python\transformers/dependency_versions_check.py", line 16, in <module>
  File "C:\Users\runneradmin\AppData\Local\Temp\pip-target-k9ekwdk7\lib\python\transformers/utils/__init__.py", line 34, in <module>
  File "C:\Users\runneradmin\AppData\Local\Temp\pip-target-k9ekwdk7\lib\python\transformers/utils/generic.py", line 462, in <module>
  File "C:\Users\Valdemar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\.python_dependencies\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Valdemar\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\.python_dependencies\torch\lib\fbgemm.dll" or one of its dependencies.
Repository data: C:\Users\Valdemar\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org not found, sync required!

```

Looks like there is an issue with library fbgemm.dll. It is present in my filesystem:
![image](https://github.com/user-attachments/assets/333bb9c7-191b-486a-a561-9eaf3b83f96d)

So I assume there is an issue with some dependencies.

I will try to debug this problem further, just wanted to keep it documented here in case someone encounters this issue too.

### Steps to Reproduce

1. Download latest plugin module
2. Install with blender 4.2.1 LTS
3. Click "Download Stable Diffusion"

### Expected Behavior

Stable Diffusion should be downloading

### Addon Version

Windows (CUDA)

### Blender Version

Blender 4.1+

### GPU

NVIDIA

**Comment by TuxDevelopment** [comment]
I just encountered the same issue, the dll that is most likely missing is libomp140.x86_64.dll

I downloaded it from https://www.dllme.com/dll/files/libomp140_x86_64 and put the .dll in the same directory as fbgemm and was able to resolve the issue.

**Comment by vladyslav-zaichyk** [comment]
@TuxDevelopment thanks! I did the same and the problem was solved.

I also tried to enable developer extras and download dependencies manually, but it did not work. Only the solution above helped.
