### ISSUE TITLE
Exception: Uninitialized input image

### ISSUE THREAD

**Issue by gerroon** [carson-katri/dream-textures#822]
### Description

![image](https://github.com/user-attachments/assets/7e398772-62c3-475d-b779-c0f6f329f347)

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\future.py", line 105, in run_callbacks
    done_callback(self)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\diffusers_backend.py", line 244, in on_done
    callback(future.result(last_only=True))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\future.py", line 46, in result
    raise self._exception
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\future.py", line 92, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\diffusers_backend.py", line 246, in on_exception
    callback(exception)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\operators\project.py", line 388, in callback
    raise results
Exception: Uninitialized input image
```

### Steps to Reproduce

Add a model
In the viewport camera mode
N panel Dream
Project dream texture in edit mode

### Expected Behavior

It should project the generated texture?

### Addon Version

Windows (CUDA)

### Blender Version

Blender 4.1+

### GPU

NVIDIA

**Comment by carson-katri** [comment]
Can you share the part of the error that appears before:
```
The above exception was the direct cause of the following exception:
```

**Comment by gerroon** [comment]
Hi,

Thanks for looking into it

```
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:03<00:00,  1.99it/s]
An ImageBuf was destroyed with a pending error message that was never
retrieved via ImageBuf::geterror(). This was the error message:
Could not initialize ImageBuf: the provided ImageSpec needs a valid width, height, depth, nchannels, format.
Cannot set_pixels() on an uninitialized ImageBuf
Exception: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\actor.py", line 211, in _receive
    for res in iter(response):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\actions\depth_to_image.py", line 351, in depth_to_image
    depth = image_to_np(depth, mode="L", size=rounded_size, to_color_space=None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\image_utils.py", line 867, in image_to_np
    array = resize(array, size)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\image_utils.py", line 520, in resize
    raise Exception(image_out.geterror())
Exception: Uninitialized input image


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\future.py", line 92, in run_callbacks
    exception_callback(self, exception)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\diffusers_backend.py", line 246, in on_exception
    callback(exception)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\operators\project.py", line 388, in callback
    raise results
Exception: Uninitialized input image
Exception: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\actor.py", line 211, in _receive
    for res in iter(response):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\generator_process\actions\depth_to_image.py", line 351, in depth_to_image
    depth = image_to_np(depth, mode="L", size=rounded_size, to_color_space=None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\image_utils.py", line 867, in image_to_np
    array = resize(array, size)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\dream_textures\image_utils.py", line 520, in resize
    raise Exception(image_out.geterror())
Exception: Uninitialized input image

```
> Can you share the part of the error that appears before:
> 
> ```
> The above exception was the direct cause of the following exception:
> ```

**Comment by NullSenseStudio** [comment]
As far as I can tell this part of the error is for the `image_in` variable of the resize function.
```
An ImageBuf was destroyed with a pending error message that was never
retrieved via ImageBuf::geterror(). This was the error message:
Could not initialize ImageBuf: the provided ImageSpec needs a valid width, height, depth, nchannels, format.
Cannot set_pixels() on an uninitialized ImageBuf
```
The only way I can replicate this is by creating an ImageBuf with at least one of the dimensions or channels set to 0, though I can't figure out how to cause that through texture projecting.
